package com.hk.domain.queue;
// Generated 15-Apr-2013 01:46:24 by Hibernate Tools 3.2.4.CR1


import com.hk.domain.user.User;

import javax.persistence.*;

/**
 * ActionTask generated by hbm2java
 */
@Entity
@Table(name = "action_task")
public class ActionTask implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "name", nullable = false, length = 90)
    private String name;

    @Column(name = "priority")
    private Long priority;

    @Column(name = "range")
    private Long range;

    @Column(name = "hierarchy")
    private Long hierarchy;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getPriority() {
        return this.priority;
    }

    public void setPriority(Long priority) {
        this.priority = priority;
    }

    public Long getRange() {
        return this.range;
    }

    public void setRange(Long range) {
        this.range = range;
    }

    public Long getHierarchy() {
        return this.hierarchy;
    }

    public void setHierarchy(Long hierarchy) {
        this.hierarchy = hierarchy;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ActionTask that = (ActionTask) o;

        return id.equals(that.id);

    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }
    
    @Override
	public String toString() {
		return this.id != null ? this.id.toString() : "";
	}


}


