package com.hk.domain.queue;
// Generated 15-Apr-2013 01:46:24 by Hibernate Tools 3.2.4.CR1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ActionQueue generated by hbm2java
 */
@Entity
@Table(name = "action_queue")
public class ActionQueue implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "current_action_item_id", nullable = false)
    private ActionItem actionItem;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "traffic_state_id")
    private TrafficState trafficState;

    @Column(name = "shipping_order_id", nullable = false)
    private Long shippingOrderId;

    @Column(name = "bucket_id", nullable = false)
    private Long bucketId;

    @Column(name = "reporter", nullable = false)
    private Long reporter;

    @Column(name = "flagged")
    private Long flagged;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "first_push_date", length = 19)
    private Date firstPushDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_push_date", length = 19)
    private Date lastPushDate;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actionQueue")
    private Set<Watcher> watchers = new HashSet<Watcher>(0);

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ActionItem getActionItem() {
        return this.actionItem;
    }

    public void setActionItem(ActionItem actionItem) {
        this.actionItem = actionItem;
    }

    public TrafficState getTrafficState() {
        return this.trafficState;
    }

    public void setTrafficState(TrafficState trafficState) {
        this.trafficState = trafficState;
    }

    public Long getShippingOrderId() {
        return this.shippingOrderId;
    }

    public void setShippingOrderId(Long shippingOrderId) {
        this.shippingOrderId = shippingOrderId;
    }

    public Long getBucketId() {
        return this.bucketId;
    }

    public void setBucketId(Long bucketId) {
        this.bucketId = bucketId;
    }

    public Long getReporter() {
        return this.reporter;
    }

    public void setReporter(Long reporter) {
        this.reporter = reporter;
    }

    public Long getFlagged() {
        return this.flagged;
    }

    public void setFlagged(Long flagged) {
        this.flagged = flagged;
    }

    public Date getFirstPushDate() {
        return this.firstPushDate;
    }

    public void setFirstPushDate(Date firstPushDate) {
        this.firstPushDate = firstPushDate;
    }

    public Date getLastPushDate() {
        return this.lastPushDate;
    }

    public void setLastPushDate(Date lastPushDate) {
        this.lastPushDate = lastPushDate;
    }

    public Set<Watcher> getWatchers() {
        return this.watchers;
    }

    public void setWatchers(Set<Watcher> watchers) {
        this.watchers = watchers;
    }


}


