package com.hk.domain.queue;
// Generated 15-Apr-2013 01:46:24 by Hibernate Tools 3.2.4.CR1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ActionItem generated by hbm2java
 */
@Entity
@Table(name = "action_item")
public class ActionItem implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "next_action_item_id")
    private ActionItem actionItem;

    @Column(name = "name", nullable = false, length = 90)
    private String name;

    @Column(name = "priority")
    private Long priority;

    @Column(name = "acknowledged")
    private Byte acknowledged;

    @Column(name = "range")
    private Long range;

    @Column(name = "hierarchy")
    private Long hierarchy;

    @Column(name = "acknowledged_by")
    private Long acknowledgedBy;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actionItem")
    private Set<ActionItem> actionItems = new HashSet<ActionItem>(0);

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "actionItem")
    private Set<ActionQueue> actionQueues = new HashSet<ActionQueue>(0);

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ActionItem getActionItem() {
        return this.actionItem;
    }

    public void setActionItem(ActionItem actionItem) {
        this.actionItem = actionItem;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getPriority() {
        return this.priority;
    }

    public void setPriority(Long priority) {
        this.priority = priority;
    }

    public Byte getAcknowledged() {
        return this.acknowledged;
    }

    public void setAcknowledged(Byte acknowledged) {
        this.acknowledged = acknowledged;
    }

    public Long getRange() {
        return this.range;
    }

    public void setRange(Long range) {
        this.range = range;
    }

    public Long getHierarchy() {
        return this.hierarchy;
    }

    public void setHierarchy(Long hierarchy) {
        this.hierarchy = hierarchy;
    }

    public Long getAcknowledgedBy() {
        return this.acknowledgedBy;
    }

    public void setAcknowledgedBy(Long acknowledgedBy) {
        this.acknowledgedBy = acknowledgedBy;
    }

    public Set<ActionItem> getActionItems() {
        return this.actionItems;
    }

    public void setActionItems(Set<ActionItem> actionItems) {
        this.actionItems = actionItems;
    }

    public Set<ActionQueue> getActionQueues() {
        return this.actionQueues;
    }

    public void setActionQueues(Set<ActionQueue> actionQueues) {
        this.actionQueues = actionQueues;
    }


}


