package com.hk.domain.queue;
// Generated 10-Apr-2013 13:58:43 by Hibernate Tools 3.2.4.CR1


import com.akube.framework.gson.JsonSkip;

import javax.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Bucket generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="bucket")
public class Bucket  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name="name", length=45)
    private String name;

    @Column(name="description")
    private String description;

    @JsonSkip
    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "bucket_constituents", uniqueConstraints = @UniqueConstraint(columnNames = {"bucket_id", "param_id"}), joinColumns = {@JoinColumn(name = "bucket_id", nullable = false, updatable = false)}, inverseJoinColumns = {@JoinColumn(name = "param_id", nullable = false, updatable = false)})
    private Set<Param> params = new HashSet<Param>(0);


    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set<Param> getParams() {
        return params;
    }

    public void setParams(Set<Param> params) {
        this.params = params;
    }
}


