package com.hk.domain.queue;
// Generated 15-Apr-2013 01:46:24 by Hibernate Tools 3.2.4.CR1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * TrafficState generated by hbm2java
 */
@Entity
@Table(name = "traffic_state")
public class TrafficState implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private Long id;


    @Column(name = "name", length = 45)
    private String name;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }



}


