package com.hk.domain.queue;
// Generated 15-Apr-2013 01:46:24 by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Watcher generated by hbm2java
 */
@Entity
@Table(name="watcher")
public class Watcher  implements java.io.Serializable {


 
    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    private Long id;
 
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="action_item_id", nullable=false)
    private ActionItem actionItem;
 
    
    @Column(name="user_id", nullable=false)
    private Long userId;
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public ActionItem getActionItem() {
        return this.actionItem;
    }
    
    public void setActionItem(ActionItem actionItem) {
        this.actionItem = actionItem;
    }
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }




}


