package com.hk.domain.analytics;
// Generated 22 Nov, 2012 2:21:02 PM by Hibernate Tools 3.2.4.CR1


import com.hk.domain.user.User;
import com.hk.domain.catalog.product.Product;
import com.hk.domain.catalog.category.Category;
import com.hk.domain.order.Order;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.*;

/**
 * TrafficTracking generated by hbm2java
 */
@Entity
@Table (name = "traffic_tracking")
public class TrafficTracking implements java.io.Serializable {


	@Id
	@GeneratedValue (strategy = IDENTITY)

	@Column (name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "user_id")
	private User user;

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "order_id")
	private Order order;

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "product_id")
	private Product product;

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "primary_category")
	private Category category;


	@Column (name = "src_url", length = 100)
	private String srcUrl;


	@Column (name = "traffic_src", nullable = false, length = 20)
	private String trafficSrc;


	@Column (name = "traffic_src_details", length = 45)
	private String trafficSrcDetails;


	@Column (name = "traffic_src_paid", nullable = false)
	private Boolean trafficSrcPaid;


	@Column (name = "landing_url", nullable = false, length = 100)
	private String landingUrl;


	@Column (name = "ip", nullable = false, length = 45)
	private String ip;


	@Column (name = "session_id", nullable = false, length = 45)
	private String sessionId;

	@Temporal (TemporalType.TIMESTAMP)
	@Column (name = "create_dt", nullable = false, length = 19)
	private Date createDt;

	@Temporal (TemporalType.TIMESTAMP)
	@Column (name = "update_dt", nullable = false, length = 19)
	private Date updateDt;

	@OneToMany (cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "trafficTracking")
	private Set<UserBrowsingHistory> userBrowsingHistories = new HashSet<UserBrowsingHistory>(0);

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getSrcUrl() {
		return this.srcUrl;
	}

	public void setSrcUrl(String srcUrl) {
		this.srcUrl = srcUrl;
	}

	public String getTrafficSrc() {
		return this.trafficSrc;
	}

	public void setTrafficSrc(String trafficSrc) {
		this.trafficSrc = trafficSrc;
	}

	public String getTrafficSrcDetails() {
		return this.trafficSrcDetails;
	}

	public void setTrafficSrcDetails(String trafficSrcDetails) {
		this.trafficSrcDetails = trafficSrcDetails;
	}

	public Boolean getTrafficSrcPaid() {
		return this.trafficSrcPaid;
	}

	public void setTrafficSrcPaid(Boolean trafficSrcPaid) {
		this.trafficSrcPaid = trafficSrcPaid;
	}

	public String getLandingUrl() {
		return this.landingUrl;
	}

	public void setLandingUrl(String landingUrl) {
		this.landingUrl = landingUrl;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	public Set<UserBrowsingHistory> getUserBrowsingHistories() {
		return this.userBrowsingHistories;
	}

	public void setUserBrowsingHistories(Set<UserBrowsingHistory> userBrowsingHistories) {
		this.userBrowsingHistories = userBrowsingHistories;
	}


}


