package com.hk.domain.analytics;

// Generated 22 Nov, 2012 2:21:02 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserBrowsingHistory generated by hbm2java
 */
@Entity
@Table(name = "user_browsing_history", uniqueConstraints = @UniqueConstraint(columnNames = {"traffic_tracking_id", "page_url"}))
public class UserBrowsingHistory implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @Column(name = "traffic_tracking_id", nullable = false)
  private Long trafficTrackingId;

  @Column(name = "page_url", nullable = false, length = 500)
  private String pageUrl;

  @Column(name = "primary_category", length = 80)
  private String primaryCategory;

  @Column(name = "product_id", length = 20)
  private String productId;

  @Column(name = "product_pos", length = 45)
  private String productPosition;

  @Column(name = "product_referrer_id")
  private Long productReferrerId;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "create_dt", nullable = false, length = 19)
  private Date createDt;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "update_dt", nullable = false, length = 19)
  private Date updateDt;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Long getTrafficTrackingId() {
    return this.trafficTrackingId;
  }

  public void setTrafficTrackingId(Long trafficTrackingId) {
    this.trafficTrackingId = trafficTrackingId;
  }

  public String getPageUrl() {
    return this.pageUrl;
  }

  public void setPageUrl(String pageUrl) {
    this.pageUrl = pageUrl;
  }

  public String getPrimaryCategory() {
    return this.primaryCategory;
  }

  public void setPrimaryCategory(String primaryCategory) {
    this.primaryCategory = primaryCategory;
  }

  public String getProductId() {
    return this.productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }

  public String getProductPosition() {
    return productPosition;
  }

  public void setProductPosition(String productPosition) {
    this.productPosition = productPosition;
  }

  public Long getProductReferrerId() {
    return productReferrerId;
  }

  public void setProductReferrerId(Long productReferrerId) {
    this.productReferrerId = productReferrerId;
  }

  public Date getCreateDt() {
    return this.createDt;
  }

  public void setCreateDt(Date createDt) {
    this.createDt = createDt;
  }

  public Date getUpdateDt() {
    return this.updateDt;
  }

  public void setUpdateDt(Date updateDt) {
    this.updateDt = updateDt;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("id : " + id + " #");
    builder.append("trafficTrackingId : " + trafficTrackingId + " #");
    builder.append("pageUrl : " + pageUrl + " #");
    builder.append("primaryCategory : " + primaryCategory + " #");
    builder.append("productId : " + productId + " #");

    return builder.toString();
  }

}
