package com.hk.domain.subscription;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subscription generated by hbm2java
 */
@Entity
@Table(name="subscription")
public class Subscription  implements java.io.Serializable {



    @Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="id", unique=true, nullable=false)
    private Long id;


    @Column(name="user_id", nullable=false)
    private Long userId;


    @Column(name="base_order_id", nullable=false)
    private Long baseOrderId;


    @Column(name="address_id", nullable=false)
    private Long addressId;


    @Column(name="subscription_status_id", nullable=false)
    private Long subscriptionStatusId;


    @Column(name="product_variant_id", nullable=false, length=20)
    private String productVariantId;


    @Column(name="qty", nullable=false)
    private Long qty;


    @Column(name="qty_per_delivery", nullable=false)
    private Long qtyPerDelivery;


    @Column(name="frequency_days", nullable=false)
    private Long frequencyDays;


    @Column(name="subscription_price", nullable=false, precision=10)
    private Double subscriptionPrice;


    @Column(name="subscription_discount_percent", nullable=false, precision=7, scale=4)
    private Double subscriptionDiscountPercent;


    @Column(name="hk_discount_at_subscription", nullable=false, precision=7, scale=4)
    private Double hkDiscountAtSubscription;


    @Column(name="hk_price_at_subscription", nullable=false, precision=10)
    private Double hkPriceAtSubscription;


    @Column(name="cost_price_at_subscription", nullable=false, precision=10)
    private Double costPriceAtSubscription;


    @Column(name="marked_price_at_subscription", nullable=false, precision=10)
    private Double markedPriceAtSubscription;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", nullable=false, length=19)
    private Date createDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    private Date updateDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", nullable=false, length=19)
    private Date startDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="next_shipment_date", length=19)
    private Date nextShipmentDate;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public Long getBaseOrderId() {
        return this.baseOrderId;
    }

    public void setBaseOrderId(Long baseOrderId) {
        this.baseOrderId = baseOrderId;
    }
    public Long getAddressId() {
        return this.addressId;
    }

    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }
    public Long getSubscriptionStatusId() {
        return this.subscriptionStatusId;
    }

    public void setSubscriptionStatusId(Long subscriptionStatusId) {
        this.subscriptionStatusId = subscriptionStatusId;
    }
    public String getProductVariantId() {
        return this.productVariantId;
    }

    public void setProductVariantId(String productVariantId) {
        this.productVariantId = productVariantId;
    }
    public Long getQty() {
        return this.qty;
    }

    public void setQty(Long qty) {
        this.qty = qty;
    }
    public Long getQtyPerDelivery() {
        return this.qtyPerDelivery;
    }

    public void setQtyPerDelivery(Long qtyPerDelivery) {
        this.qtyPerDelivery = qtyPerDelivery;
    }
    public Long getFrequencyDays() {
        return this.frequencyDays;
    }

    public void setFrequencyDays(Long frequencyDays) {
        this.frequencyDays = frequencyDays;
    }
    public Double getSubscriptionPrice() {
        return this.subscriptionPrice;
    }

    public void setSubscriptionPrice(Double subscriptionPrice) {
        this.subscriptionPrice = subscriptionPrice;
    }
    public Double getSubscriptionDiscountPercent() {
        return this.subscriptionDiscountPercent;
    }

    public void setSubscriptionDiscountPercent(Double subscriptionDiscountPercent) {
        this.subscriptionDiscountPercent = subscriptionDiscountPercent;
    }
    public Double getHkDiscountAtSubscription() {
        return this.hkDiscountAtSubscription;
    }

    public void setHkDiscountAtSubscription(Double hkDiscountAtSubscription) {
        this.hkDiscountAtSubscription = hkDiscountAtSubscription;
    }
    public Double getHkPriceAtSubscription() {
        return this.hkPriceAtSubscription;
    }

    public void setHkPriceAtSubscription(Double hkPriceAtSubscription) {
        this.hkPriceAtSubscription = hkPriceAtSubscription;
    }
    public Double getCostPriceAtSubscription() {
        return this.costPriceAtSubscription;
    }

    public void setCostPriceAtSubscription(Double costPriceAtSubscription) {
        this.costPriceAtSubscription = costPriceAtSubscription;
    }
    public Double getMarkedPriceAtSubscription() {
        return this.markedPriceAtSubscription;
    }

    public void setMarkedPriceAtSubscription(Double markedPriceAtSubscription) {
        this.markedPriceAtSubscription = markedPriceAtSubscription;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getNextShipmentDate() {
        return this.nextShipmentDate;
    }

    public void setNextShipmentDate(Date nextShipmentDate) {
        this.nextShipmentDate = nextShipmentDate;
    }

}

