package com.hk.domain.subscription;


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.hk.domain.order.Order;

/**
 * SubscriptionOrder generated by hbm2java
 */
@Entity
@Table(name="subscription_order")
public class SubscriptionOrder  implements java.io.Serializable {



    @Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="id", unique=true, nullable=false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="subscription_id", nullable=false)
    private Subscription subscription;

    @OneToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="base_order_id", nullable=false)
    private Order baseOrder;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="subscription_order_status_id", nullable=false)
    private SubscriptionOrderStatus subscriptionOrderStatus;


    @Column(name="hk_price_now", nullable=false, precision=10)
    private Double hkPriceNow;


    @Column(name="hk_discount_now", nullable=false, precision=7, scale=4)
    private Double hkDiscountNow;


    @Column(name="marked_price_now", nullable=false, precision=10)
    private Double markedPriceNow;


    @Column(name="cost_price_now", nullable=false, precision=10)
    private Double costPriceNow;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19, nullable = false)
    private Date createDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    private Date updateDate;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    public Subscription getSubscription() {
        return this.subscription;
    }

    public void setSubscription(Subscription subscription) {
        this.subscription = subscription;
    }
    public Order getBaseOrder() {
        return this.baseOrder;
    }

    public void setBaseOrder(Order baseOrder) {
        this.baseOrder = baseOrder;
    }
    public SubscriptionOrderStatus getSubscriptionOrderStatus() {
        return this.subscriptionOrderStatus;
    }

    public void setSubscriptionOrderStatus(SubscriptionOrderStatus subscriptionOrderStatus) {
        this.subscriptionOrderStatus = subscriptionOrderStatus;
    }
    public Double getHkPriceNow() {
        return this.hkPriceNow;
    }

    public void setHkPriceNow(Double hkPriceNow) {
        this.hkPriceNow = hkPriceNow;
    }
    public Double getHkDiscountNow() {
        return this.hkDiscountNow;
    }

    public void setHkDiscountNow(Double hkDiscountNow) {
        this.hkDiscountNow = hkDiscountNow;
    }
    public Double getMarkedPriceNow() {
        return this.markedPriceNow;
    }

    public void setMarkedPriceNow(Double markedPriceNow) {
        this.markedPriceNow = markedPriceNow;
    }
    public Double getCostPriceNow() {
        return this.costPriceNow;
    }

    public void setCostPriceNow(Double costPriceNow) {
        this.costPriceNow = costPriceNow;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


