package com.hk.domain.subscription;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubscriptionLifecycle generated by hbm2java
 */
@Entity
@Table(name="subscription_lifecycle")
public class SubscriptionLifecycle  implements java.io.Serializable {



    @Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="id", unique=true, nullable=false)
    private Long id;


    @Column(name="subscription_id", nullable=false)
    private Long subscriptionId;


    @Column(name="subscription_lifecycle_activity_id", nullable=false)
    private Long subscriptionLifecycleActivityId;


    @Column(name="user_id", nullable=false)
    private Long userId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    private Date date;


    @Column(name="comments", length=65535)
    private String comments;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    public Long getSubscriptionId() {
        return this.subscriptionId;
    }

    public void setSubscriptionId(Long subscriptionId) {
        this.subscriptionId = subscriptionId;
    }
    public Long getSubscriptionLifecycleActivityId() {
        return this.subscriptionLifecycleActivityId;
    }

    public void setSubscriptionLifecycleActivityId(Long subscriptionLifecycleActivityId) {
        this.subscriptionLifecycleActivityId = subscriptionLifecycleActivityId;
    }
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }




}