package com.hk.domain.subscription;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubscriptionLifecycleActivity generated by hbm2java
 */
@Entity
@Table(name="subscription_lifecycle_activity")
public class SubscriptionLifecycleActivity  implements java.io.Serializable {



    @Id

    @Column(name="id", unique=true, nullable=false)
    private Long id;


    @Column(name="name", nullable=false, length=100)
    private String name;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }




}

