package com.hk.domain.affiliate;
// Generated Aug 1, 2011 3:08:36 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * DefaultCategoryCommission generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "default_category_commission")
public class DefaultCategoryCommission implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @Column(name = "commission_first", nullable = false, precision = 22, scale = 0)
  private double commissionFirstTime;

  @Column(name = "commission_second", precision = 22, scale = 0)
  private Double commissionLatterTime;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "affiliate_category_name", nullable = false)
  private AffiliateCategory affiliateCategory;

  @Transient
  private boolean selected;

/*
  @OneToMany(fetch = FetchType.LAZY, mappedBy = "affiliateCategoryName")
  private List<AffiliateCategory> affiliateCategories = new ArrayList<AffiliateCategory>(0);

  public List<AffiliateCategory> getAffiliateCategories() {
    return affiliateCategories;
  }

  public void setAffiliateCategories(List<AffiliateCategory> affiliateCategories) {
    this.affiliateCategories = affiliateCategories;
  }
*/

  public boolean isSelected() {
    return selected;
  }

  public void setSelected(boolean selected) {
    this.selected = selected;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public double getCommissionFirstTime() {
    return commissionFirstTime;
  }

  public void setCommissionFirstTime(double commissionFirstTime) {
    this.commissionFirstTime = commissionFirstTime;
  }

  public Double getCommissionLatterTime() {
    return commissionLatterTime;
  }

  public void setCommissionLatterTime(Double commissionLatterTime) {
    this.commissionLatterTime = commissionLatterTime;
  }

  public AffiliateCategory getAffiliateCategory() {
    return affiliateCategory;
  }

  public void setAffiliateCategory(AffiliateCategory affiliateCategory) {
    this.affiliateCategory = affiliateCategory;
  }
}