package com.hk.domain.hkDelivery;
// Generated Aug 14, 2012 3:05:58 PM by Hibernate Tools 3.2.4.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConsignmentTracking generated by hbm2java
 */
@Entity
@Table(name = "consignment_tracking")
public class ConsignmentTracking implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "consignment_id", nullable = false)
    private Consignment consignment;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "source_hub_id")
    private Hub sourceHubId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "destination_hub_id")
    private Hub destinationHubId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 19)
    private Date createDate;


    @Column(name = "remarks", length = 45)
    private String remarks;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Consignment getConsignment() {
        return this.consignment;
    }

    public void setConsignment(Consignment consignment) {
        this.consignment = consignment;
    }

    public Hub getSourceHubId() {
        return this.sourceHubId;
    }

    public void setSourceHubId(Hub sourceHubId) {
        this.sourceHubId = sourceHubId;
    }

    public Hub getDestinationHubId() {
        return this.destinationHubId;
    }

    public void setDestinationHubId(Hub destinationHubId) {
        this.destinationHubId = destinationHubId;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }


}


