package com.hk.domain.hkDelivery;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Id;
import javax.persistence.Column;


/**
 * RunsheetStatus generated by hbm2java
 */
@Entity
@Table(name = "consignment_lifecycle_status")
public class ConsignmentLifecycleStatus {
    @Id

    @Column(name = "id", unique = true, nullable = false)
    private Long id;


    @Column(name = "status", nullable = false, length = 100)
    private String status;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return id == null ? "" : id.toString();
    }

}
