package com.hk.domain.hkDelivery;
// Generated Aug 14, 2012 1:18:49 PM by Hibernate Tools 3.2.4.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consignment generated by hbm2java
 */
@Entity
@Table(name = "consignment")
public class Consignment implements java.io.Serializable, Comparable<Consignment> {


    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "awb_number", nullable = false, unique = true)
    private String awbNumber;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hub_id", nullable = false)
    private Hub hub;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "runsheet_id")
    private Runsheet runsheet;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "consignment_status_id", nullable = false)
    private ConsignmentStatus consignmentStatus;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    private Date createDate;


    @Column(name = "cnn_number", nullable = false, length = 25)
    private String cnnNumber;


    @Column(name = "amount", nullable = false, precision = 22, scale = 0)
    private double amount;


    @Column(name = "payment_mode", nullable = false, length = 15)
    private String paymentMode;

    @Column(name = "address")
    private String address;

    @Column(name = "owner", length = 100)
    private String owner;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "target_delivery_date", length = 19)
    private Date targetDeliveryDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "delivery_date", length = 19)
    private Date deliveryDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hkdelivery_payment_reconciliation_id")
    private HkdeliveryPaymentReconciliation hkdeliveryPaymentReconciliation;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAwbNumber() {
        return this.awbNumber;
    }

    public void setAwbNumber(String awbNumber) {
        this.awbNumber = awbNumber;
    }

    public Hub getHub() {
        return this.hub;
    }

    public void setHub(Hub hub) {
        this.hub = hub;
    }

    public Runsheet getRunsheet() {
        return this.runsheet;
    }

    public void setRunsheet(Runsheet runsheet) {
        this.runsheet = runsheet;
    }

    public ConsignmentStatus getConsignmentStatus() {
        return this.consignmentStatus;
    }

    public void setConsignmentStatus(ConsignmentStatus consignmentStatus) {
        this.consignmentStatus = consignmentStatus;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCnnNumber() {
        return this.cnnNumber;
    }

    public void setCnnNumber(String cnnNumber) {
        this.cnnNumber = cnnNumber;
    }

    public double getAmount() {
        return this.amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public String getPaymentMode() {
        return this.paymentMode;
    }

    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }

    public HkdeliveryPaymentReconciliation getHkdeliveryPaymentReconciliation() {
        return hkdeliveryPaymentReconciliation;
    }

    public void setHkdeliveryPaymentReconciliation(HkdeliveryPaymentReconciliation hkdeliveryPaymentReconciliation) {
        this.hkdeliveryPaymentReconciliation = hkdeliveryPaymentReconciliation;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Date getDeliveryDate() {
        return deliveryDate;
    }

    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    @Override
    public String toString() {
        return id == null ? "" : id.toString();
    }

    public int compareTo(Consignment o) {
        return this.id.compareTo(o.getId());
    }
    public Date getTargetDeliveryDate() {
        return targetDeliveryDate;
    }

    public void setTargetDeliveryDate(Date targetDeliveryDate) {
        this.targetDeliveryDate = targetDeliveryDate;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }
}


