package com.hk.domain.hkDelivery;
// Generated Aug 14, 2012 1:18:49 PM by Hibernate Tools 3.2.4.CR1


import com.hk.domain.courier.Awb;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consignment generated by hbm2java
 */
@Entity
@Table(name = "consignment")
public class Consignment implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "awb_number", nullable = false, unique = true)
    private String awbNumber;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "payment_reconciliation_id")
    private PaymentReconciliation paymentReconciliation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hub_id", nullable = false)
    private Hub hub;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "runsheet_id")
    private Runsheet runsheet;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "consignment_status_id", nullable = false)
    private ConsignmentStatus consignmentStatus;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    private Date createDate;


    @Column(name = "cnn_number", nullable = false, length = 25)
    private String cnnNumber;


    @Column(name = "amount", nullable = false, precision = 22, scale = 0)
    private double amount;


    @Column(name = "payment_mode", nullable = false, length = 15)
    private String paymentMode;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAwbNumber() {
        return this.awbNumber;
    }

    public void setAwbNumber(String awbNumber) {
        this.awbNumber = awbNumber;
    }

    public PaymentReconciliation getPaymentReconciliation() {
        return this.paymentReconciliation;
    }

    public void setPaymentReconciliation(PaymentReconciliation paymentReconciliation) {
        this.paymentReconciliation = paymentReconciliation;
    }

    public Hub getHub() {
        return this.hub;
    }

    public void setHub(Hub hub) {
        this.hub = hub;
    }

    public Runsheet getRunsheet() {
        return this.runsheet;
    }

    public void setRunsheet(Runsheet runsheet) {
        this.runsheet = runsheet;
    }

    public ConsignmentStatus getConsignmentStatus() {
        return this.consignmentStatus;
    }

    public void setConsignmentStatus(ConsignmentStatus consignmentStatus) {
        this.consignmentStatus = consignmentStatus;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCnnNumber() {
        return this.cnnNumber;
    }

    public void setCnnNumber(String cnnNumber) {
        this.cnnNumber = cnnNumber;
    }

    public double getAmount() {
        return this.amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public String getPaymentMode() {
        return this.paymentMode;
    }

    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }


}


