package com.hk.domain.hkDelivery;
// Generated Aug 9, 2012 6:19:09 PM by Hibernate Tools 3.2.4.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConsignmentTracking generated by hbm2java
 */
@Entity
@Table(name="consignment_tracking")
public class ConsignmentTracking  implements java.io.Serializable {


 
    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    private Long id;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    private Date createDate;
 
    
    @Column(name="remarks", length=200)
    private String remarks;
 
    
    @Column(name="source_hub_id")
    private Long sourceHubId;
 
    
    @Column(name="destination_id")
    private Long destinationId;
 
    
    @Column(name="consignment_id", nullable=false)
    private Long consignmentId;
 
    
    @Column(name="user_id")
    private Long userId;
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Long getSourceHubId() {
        return this.sourceHubId;
    }
    
    public void setSourceHubId(Long sourceHubId) {
        this.sourceHubId = sourceHubId;
    }
    public Long getDestinationId() {
        return this.destinationId;
    }
    
    public void setDestinationId(Long destinationId) {
        this.destinationId = destinationId;
    }
    public Long getConsignmentId() {
        return this.consignmentId;
    }
    
    public void setConsignmentId(Long consignmentId) {
        this.consignmentId = consignmentId;
    }
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }




}


