package com.hk.domain.hkDelivery;
// Generated Aug 14, 2012 3:05:58 PM by Hibernate Tools 3.2.4.CR1


import com.hk.domain.user.User;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConsignmentTracking generated by hbm2java
 */
@Entity
@Table(name = "consignment_tracking")
public class ConsignmentTracking implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "consignment_id", nullable = false)
    private Consignment consignment;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "source_hub_id")
    private Hub sourceHub;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "destination_hub_id")
    private Hub destinationHub;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 19)
    private Date createDate;


    @Column(name = "remarks", length = 150)
    private String remarks;

    @Column(name = "ndr_resolution", length = 100)
    private String ndrResolution;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "consignment_lifecycle_status_id")
    private ConsignmentLifecycleStatus consignmentLifecycleStatus;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "runsheet_id", nullable = true)
    private Runsheet runsheet;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Consignment getConsignment() {
        return this.consignment;
    }

    public void setConsignment(Consignment consignment) {
        this.consignment = consignment;
    }

    public Hub getSourceHub() {
        return sourceHub;
    }

    public void setSourceHub(Hub sourceHub) {
        this.sourceHub = sourceHub;
    }

    public Hub getDestinationHub() {
        return destinationHub;
    }

    public void setDestinationHub(Hub destinationHub) {
        this.destinationHub = destinationHub;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public ConsignmentLifecycleStatus getConsignmentLifecycleStatus() {
        return consignmentLifecycleStatus;
    }

    public void setConsignmentLifecycleStatus(ConsignmentLifecycleStatus consignmentLifecycleStatus) {
        this.consignmentLifecycleStatus = consignmentLifecycleStatus;
    }

    public Runsheet getRunsheet() {
        return runsheet;
    }

    public void setRunsheet(Runsheet runsheet) {
        this.runsheet = runsheet;
    }

    public String getNdrResolution() {
        return ndrResolution;
    }

    public void setNdrResolution(String ndrResolution) {
        this.ndrResolution = ndrResolution;
    }

}


