package com.hk.domain.hkDelivery;
// Generated Aug 3, 2012 3:17:40 PM by Hibernate Tools 3.2.4.CR1


import com.hk.domain.hkDelivery.Consignment;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ConsignmentStatus generated by hbm2java
 */
@Entity
@Table(name = "consignment_status")
public class ConsignmentStatus implements java.io.Serializable {


    @Id

    @Column(name = "id", unique = true, nullable = false)
    private Long id;


    @Column(name = "name", nullable = false, length = 100)
    private String name;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "consignmentStatus")
    private Set<Consignment> consignments = new HashSet<Consignment>(0);

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<Consignment> getConsignments() {
        return this.consignments;
    }

    public void setConsignments(Set<Consignment> consignments) {
        this.consignments = consignments;
    }


}


