package com.hk.domain.hkDelivery;
// Generated Aug 3, 2012 3:17:40 PM by Hibernate Tools 3.2.4.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hub generated by hbm2java
 */
@Entity
@Table(name = "hub")
public class Hub implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    private Long id;


    @Column(name = "address", length = 150)
    private String address;


    @Column(name = "country", length = 45)
    private String country;


    @Column(name = "city_id", nullable = false)
    private Long cityId;


    @Column(name = "state_id", nullable = false)
    private Long stateId;


    @Column(name = "pincode_id", nullable = false)
    private Long pincodeId;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "hub")
    private Set<Consignment> consignments = new HashSet<Consignment>(0);

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "hub")
    private Set<Runsheet> runsheets = new HashSet<Runsheet>(0);

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Long getCityId() {
        return this.cityId;
    }

    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    public Long getStateId() {
        return this.stateId;
    }

    public void setStateId(Long stateId) {
        this.stateId = stateId;
    }

    public Long getPincodeId() {
        return this.pincodeId;
    }

    public void setPincodeId(Long pincodeId) {
        this.pincodeId = pincodeId;
    }

    public Set<Consignment> getConsignments() {
        return this.consignments;
    }

    public void setConsignments(Set<Consignment> consignments) {
        this.consignments = consignments;
    }

    public Set<Runsheet> getRunsheets() {
        return this.runsheets;
    }

    public void setRunsheets(Set<Runsheet> runsheets) {
        this.runsheets = runsheets;
    }


}


