package com.hk.domain;
// Generated Aug 3, 2012 3:17:40 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PaymentHasConsignment generated by hbm2java
 */
@Entity
@Table(name="payment_has_consignment")
public class PaymentHasConsignment  implements java.io.Serializable {


 
    @Id 
    
    @Column(name="id", unique=true, nullable=false)
    private Long id;
 
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_reconciliation_id", nullable=false)
    private PaymentReconciliation paymentReconciliation;
 
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="consignment_id", nullable=false)
    private Consignment consignment;
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public PaymentReconciliation getPaymentReconciliation() {
        return this.paymentReconciliation;
    }
    
    public void setPaymentReconciliation(PaymentReconciliation paymentReconciliation) {
        this.paymentReconciliation = paymentReconciliation;
    }
    public Consignment getConsignment() {
        return this.consignment;
    }
    
    public void setConsignment(Consignment consignment) {
        this.consignment = consignment;
    }




}


