package com.hk.domain.core;
// Generated Feb 18, 2012 7:05:35 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Surcharge generated by hbm2java
 */
@Entity
@Table(name = "surcharge")
public class Surcharge implements java.io.Serializable {


	@Id
	@Column(name = "id", unique = true, nullable = false)
	private Long id;


	@Column(name = "name", nullable = false, length = 45)
	private String name;


	@Column(name = "value", nullable = false, precision = 12)
	private Double value;
	
	@Override
	public String toString(){
		return this.id!=null ? this.id.toString() : "";
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}


}


