package com.hk.domain;
// Generated Jan 28, 2012 3:13:58 PM by Hibernate Tools 3.2.4.CR1


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.hk.domain.pk.TransactionBodyPk;

/**
 * TransactionBody generated by hbm2java
 */
@Entity
@Table(name = "transaction_body", uniqueConstraints = @UniqueConstraint(columnNames = {"s_no", "vch_code"}))
public class TransactionBody implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "vchCode", column = @Column(name = "vch_code", nullable = false)),
		@AttributeOverride(name = "sNo", column = @Column(name = "s_no", nullable = false))})
	private TransactionBodyPk pk;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vch_code", nullable = false, insertable = false, updatable = false)
	private TransactionHeader transactionHeader;

	@Column(name = "s_no", nullable = false, insertable = false, updatable = false)
	private Long sNo;

	@Column(name = "item_code", nullable = false, length = 12)
	private String itemCode;

	@Column(name = "qty", nullable = false)
	private Long qty;

	@Column(name = "unit", length = 40)
	private String unit;

	@Column(name = "mrp")
	private Double mrp;

	@Column(name = "rate", nullable = false)
	private Double rate;

	@Column(name = "discount")
	private Double discount;

	@Column(name = "vat")
	private Double vat;

	@Column(name = "amount", nullable = false)
	private Double amount;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	private Date createDate;

	public TransactionBodyPk getId() {
		return this.pk;
	}

	public void setId(TransactionBodyPk pk) {
		this.pk = pk;
	}

	public void setId(Long vchCode, Long sNo) {
		this.pk = new TransactionBodyPk(vchCode, sNo);
	}

	public TransactionHeader getTransactionHeader() {
		return this.transactionHeader;
	}

	public void setTransactionHeader(TransactionHeader transactionHeader) {
		this.transactionHeader = transactionHeader;
	}

	public Long getSNo() {
		return sNo;
	}

	public void setSNo(Long sNo) {
		this.sNo = sNo;
	}

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public Long getQty() {
		return this.qty;
	}

	public void setQty(Long qty) {
		this.qty = qty;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Double getMrp() {
		return this.mrp;
	}

	public void setMrp(Double mrp) {
		this.mrp = mrp;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	public Double getVat() {
		return this.vat;
	}

	public void setVat(Double vat) {
		this.vat = vat;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}
