
package com.hk.constants.report;

public class ReportConstants {

    public static final String INVOICE_ID = "INVOICE_ID";
    public static final String INVOICE_DATE = "INVOICE_DATE";
    public static final String ACCOUNTING_INVOICE_ID = "ACCOUNTING_INVOICE_ID";
    public static final String USER_ID = "USER_ID";
    public static final String ORDER_DATE = "ORDER_DATE";
    public static final String NAME = "NAME";
    public static final String PHONE = "PHONE";
    public static final String EMAIL = "EMAIL";
    public static final String ADDRESS = "ADDRESS";
    public static final String LINE1 = "LINE1";
    public static final String LINE2 = "LINE2";
    public static final String CITY = "CITY";
    public static final String STATE = "STATE";
    public static final String CATEGORY = "CATEGORY";
    public static final String ITEM_NAME = "ITEM_NAME";
    public static final String VAT_PERCENTAGE = "VAT_PERCENTAGE";
    public static final String SURCHARGE_PERCENTAGE = "SURCHARGE_PERCENTAGE";
    public static final String QTY = "QTY";
    public static final String UNIT = "UNIT";
    public static final String INVENTORY = "INVENTORY";
    public static final String MRP = "MRP";
    public static final String OFFER_PRICE = "OFFER_PRICE";
    public static final String NET_PRE_DISCOUNT = "NET_PRE_DISCOUNT";
    public static final String NET_DISCOUNT_COUPON = "NET_DISCOUNT_COUPON";
    public static final String NET_DISCOUNT_REWARD_POINTS = "NET_DISCOUNT_REWARD_POINTS";
    public static final String NET_DISCOUNT = "NET_DISCOUNT";
    public static final String NET_POST_DISCOUNT = "NET_POST_DISCOUNT";
    public static final String GROSS_PER_UNIT = "GROSS_PER_UNIT";
    public static final String TAXABLE = "TAXABLE";
    public static final String TAX_COLLECTED = "TAX_COLLECTED";
    public static final String VAT_CST = "VAT/CST";
    public static final String SURCHARGE = "SURCHARGE";
    public static final String PAYMENT_MODE = "PAYMENT_MODE";
    public static final String SHIPPING_CHARGE = "SHIPPING_CHARGE";
    public static final String COD_CHARGES = "COD_CHARGES";
    public static final String COLLECTION_CHARGE = "COLLECTION_CHARGE";
    public static final String GATEWAY_ORDER_ID = "GATEWAY_ORDER_ID";
    public static final String EXTRA_CHARGES = "EXTRA_CHARGES";
    public static final String BASE_ORDER_ID = "BASE_ORDER_ID";

    public static final String COST_PRICE = "COST PRICE";
    public static final String TAX_PAID_SUPPLIER = "TAX_PAID_SUPPLIER";
    public static final String TAX_RECOVERABLE_SUPPLIER = "TAX_RECOVERABLE_SUPPLIER";
    public static final String GROSS_MARGIN = "GROSS_MARGIN";

    public static final String ORDER_STATUS = "ORDER_STATUS";

    public static final String BRAND = "BRAND";
    public static final String VARIANT_DETAILS = "VARIANT_DETAILS";
    public static final String NET_SALES = "NET_SALES";
    public static final String MRP_SALES = "MRP_SALES";
    public static final String COST_SALES = "COST_SALES";
    public static final String TAX_PAID_SALES = "TAX_PAID_SALES";
    public static final String TAX_RECOVERABLE_SALES = "TAX_RECOVERABLE_SALES";
    public static final String TOTAL_AMOUNT = "TOTAL_AMOUNT";

    public static final String DAY_OF_WEEK = "DAY_OF_WEEK";
    public static final String TXN_COUNT = "TXN_COUNT";
    public static final String SKU_COUNT = "SKU_COUNT";
    public static final String SUM_MRP = "SUM_MRP";
    public static final String SUM_HK_PRICE = "SUM_HK_PRICE";
    public static final String SUM_HK_PRICE_POST_DISCOUNT = "SUM_HK_PRICE_POST_DISCOUNT";

    public static final String ORDER_ID = "ORDER_ID";
    public static final String AMOUNT = "AMOUNT";
    public static final String TOTAL_NO_OF_PRODUCTS = "NO_OF_PRODUCTS";
    public static final String SUM_DISCOUNT = "SUM_DISCOUNT";
    public static final String COURIER = "COURIER";
    public static final String COURIER_ID = "COURIER_ID";
    public static final String RECONCILED = "RECONCILED";
    public static final String PAYMENT_STATUS = "PAYMENT_STATUS";
    public static final String SHIPMENT_DATE = "SHIPMENT_DATE";
    public static final String DELIVERY_DATE = "DELIVERY_DATE";
    public static final String BOX_SIZE = "BOX_SIZE";
    public static final String BOX_WEIGHT = "BOX_WEIGHT(Kgs)";

    public static final String AWB = "AWB";
    public static final String SHIPPERS_REFERENCE_NUMBER = "SHIPPERS REFERENCE NUMBER";
    public static final String SHIPPER = "SHIPPER";
    public static final String CONSIGNEE_CONTACT_NAME = "CONSIGNEE CONTACT NAME";
    public static final String CONSIGNEE_NAME = "CONSIGNEE NAME";
    public static final String CONSIGNEE_ADDRESS_LINE_1 = "CONSIGNEE ADDRESS LINE 1";
    public static final String CONSIGNEE_ADDRESS_LINE_2 = "CONSIGNEE ADDRESS LINE 2";
    public static final String CONSIGNEE_ADDRESS_LINE_3 = "CONSIGNEE ADDRESS LINE 3";
    public static final String CONSIGNEE_ADDRESS_LINE_4 = "CONSIGNEE ADDRESS LINE 4";
    public static final String CONSIGNEE_CITY = "CONSIGNEE CITY";
    public static final String CONSIGNEE_PINCODE = "CONSIGNEE PINCODE";
    public static final String CONSIGNEE_PHONE_NUMBER = "CONSIGNEE PHONE NUMBER";
    public static final String CONSIGNEE_MOBILE = "CONSIGNEE MOBILE";
    public static final String PRODUCT = "PRODUCT /SKU CODE";
    public static final String WEIGHT = "WEIGHT";
    public static final String PIECE = "PIECE";
    public static final String DECLARED_VALUE = "DECLARED_VALUE";
    public static final String CONTENT_DESCRIPTION = "CONTENT_DESCRIPTION";
    public static final String COD_AMOUNT = "COD_AMOUNT";
    public static final String SHIPMENT_TYPE = "SHIPMENT_TYPE";
    public static final String NET_MARGIN = "NET_MARGIN";

    public static final String TOTAL_TIME_ELAPSED = "TIME_ELAPSED";
    public static final String ACTUAL_TIME_ELAPSED = "ACTUAL_TIME_ELAPSED";
    public static final String ORDER_PLACED_DATE = "ORDER_PLACED_DATE";
    public static final String ORDER_CONFIRMED_DATE = "ORDER_CONFIRMED_DATE";
    public static final String TOTAL_TIME_TAKEN_TO_CONFIRM = "TOTAL_TIME_TAKEN_TO_CONFIRM";
    public static final String ACTUAL_TIME_TAKEN_TO_CONFIRM = "ACTUAL_TIME_TAKEN_TO_CONFRIM";

    public static final String DAY_OF_WEEK_SUNDAY = "Sun";
    public static final String DAY_OF_WEEK_SATURDAY = "Sat";

    public static final String COD_CONFIRMED = "COD_CONFIRMED";
    public static final String COD_UNCONFIRMED = "COD_UNCONFIRMED";

    public static final int permissibleHourCount = 3;
    public static final int dayBeginHour = 10;
    public static final int dayEndHour = 21;

    public static final String TRACKING_ID = "TRACKING_ID";
    public static final String PIN_CODE = "PIN_CODE";
    public static final String DAYS_TO_DELIVER = "DAYS_TO_DELIVER";
    public static final String SALES_TYPE = "SALES_TYPE";
    public static final String MAIN_STORE = "MAIN_STORE";
    public static final String RATE = "RATE";
    public static final String SHIPPING = "SHIPPING";

    public static final String REF_NO = "Ref. No";
    public static final String CN_NO = "CNNO";
    public static final String DELIVERED_DATE = "Delivered Date ";
    public static final String STATUS = "Status";

    public static final String DEBTORS_BANK_DEPOSIT_CASH = "Debtors Bank Deposit Cash";   // cash deposit
    public static final String DEBTORS_BANK_DEPOSIT_OTHERS = "Debtors Bank Deposit Others";  //mapped to neft and cheque deposit
    public static final String DEBTORS_COD = "Debtors COD"; //mapped to COD
    public static final String DEBTORS_TECHPROCESS = "Debtors Tech Process"; // mapped to  Techprocess
    public static final String DEBTORS_COUNTER_CASH = "Debtors Counter Cash"; //mapped to counter_cash
    public static final String TECH_PROC = "Tech Proc";
    public static final String CASH_DEPOSIT = "CashDeposit";
    public static final String COD = "COD";
    public static final String BANK_DEPO = "Bank Depo";
    public static final String COUNTER_CASH = "Counter Cash";
    private static final String SHIP_DATE = "SHIP DATE";
    public static final String TOTALS_FOR_DAY = "TOTALS FOR DAY";
    public static final String IN_SHIPPED_STATUS = "IN SHIPPED STATUS";
    public static final String IN_DELIVERED_STATUS = "IN DELIVERED STATUS";
    public static final String IN_RETURNED_STATUS = "IN RETURNED STATUS";
    public static final String IN_CANCELLED_STATUS = "IN CANCELLED STATUS";
    public static final String FORWARDING_CHARGES = "FWD CHARGES";
    public static final String NET_RECEIVABLE = "NET RECEIVABLE";
    public static final String VARIANT_ID = "VARIANT ID";
    public static final String PRIMARY_CATEGORY = "PRIMARY CATEGORY";
    public static final String NOTIFICATION_REQUEST_DATE = "NOTIFICATION REQUEST DATE";
    public static final String TAX_CATEGORY = "Tax Category";
    public static final String PRODUCT_VARIANT = "PRODUCT VARIANT";
    public static final String HK_PRICE = "HK PRICE";
    public static final String TAX_RATE = "TAX RATE";
    public static final String QUANTITY = "QUANTITY";
    public static final String TAX_ADJ_PRICE = "TAX-ADJ-PRICE";
    public static final String TOTAL_SHIPPING = "TOTAL SHIPPING";
    public static final String TOTAL_COLLECTION = "TOTAL COLLECTION";
    public static final String PRODUCT_NAME = "PRODUCT NAME";
    public static final String PRODUCT_OPTIONS = "PRODUCT OPTIONS";
    public static final String SHIPPING_COLLECTION = "SHIPPING+COLLECTION PER ITEM";
    public static final String NET_CONT_MARGIN = "NET CONT MARGIN";
    public static final String PRODUCT_VARIANT_ID = "PRODUCT VARIANT ID";
    public static final String LOCATION = "LOCATION";
    public static final String HK_BARCODE = "HK BARCODE";
    public static final String COURIER_ID_STR = "Courier Id";                   

    public static final String ZONE = "ZONE";
    public static final String BARCODE = "BARCODE";
    public static final String TYPE = "TYPE";
    public static final String AIR_WAY_BILL = "AIR WAY BILL";
    public static final String SENDER  = "SENDER/ STORE_NUMBER";
    public static final String REFERENCE_NUMBER = "REFERENCE NUMBER";
    public static final String ATTENTION = "ATTENTION";
    public static final String ADDRESS_1 = "ADDRESS1";
    public static final String ADDRESS_2 = "ADDRESS2";
    public static final String ADDRESS_3 = "ADDRESS3";
    public static final String PINCODE = "PINCODE";
    public static final String TEL_NUMBER = "TEL NUMBER";
    public static final String MOBILE_NUMBER = "MOBILE NUMBER";
    public static final String CONTENT = "CONTENT";
    public static final String VENDOR_CODE = "VENDOR CODE";
    public static final String SHIPPER_NAME = "SHIPPER NAME";
    public static final String RETURN_ADDRESS1 = "RETURN_ADDRESS1";
    public static final String RETURN_ADDRESS2 = "RETURN_ADDRESS2";
    public static final String RETURN_ADDRESS3 = "RETURN_ADDRESS3";
    public static final String COLLECTABLE_VALUES = "COLLECTABLE VALUES";
    public static final String RETURN_PIN = "RETURN PIN";
    public static final String LENGTH = "LENGHT(Cms)";
    public static final String BREADTH = "BREADTH(Cms)";
    public static final String HEIGHT = "HEIGHT(Cms)";
    public static final String PIECES = "PIECES";
    public static final String AREA_CUSTOMER_CODE = "AREA CUSTOMER CODE";
    public static final String Ggn_Cod_Area_Customer_Code = "GGN373925";
    public static final String Ggn_Prepaid_Area_Customer_Code = "GGN373914";
    public static final String Mumbai_Cod_Area_Customer_Code = "BOM608322";
    public static final String Mumbai_Prepaid_Area_Customer_Code = "BOM608333";
    public static final String Delhi_Kapp_Cod_Area_Customer_Code = "DEL247435";
    public static final String Delhi_Kapp_Prepaid_Area_Customer_Code = "DEL247446";
    public static final String Ggn_Vendor_Code = "GGNWHE";
    public static final String Mumbai_Vendor_Code = "BOMWHE";
    public static final String Delhi_Kapp_Vendor_Code = "DELWHE";
    public static final String HAND_OVER_DATE = "HANDOVER DATE";
    public static final String HAND_OVER_TIME= "1650";
}
