package com.hk.domain.catalog.product;
// Generated 10 Mar, 2011 5:37:39 PM by Hibernate Tools 3.2.4.CR1

import com.akube.framework.gson.JsonSkip;
import javax.persistence.*;

/**
 * ProductImage generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "product_image")
public class ProductImage implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

    @JsonSkip
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	private Product product;

	@Column(name = "url", nullable = false, length = 45)
	private String url;

	@Column(name = "alt_text", nullable = false, length = 45)
	private String altText;

	@Column(name = "image_type")
	private Long imageType;

	@Column(name = "height")
	private Long height;

	@Column(name = "width")
	private Long width;

	@Column(name = "checksum", nullable = false, length = 45)
	private String checksum;

	@Column(name = "hidden", nullable = false)
	private boolean hidden;

	@Column(name = "uploaded", nullable = false)
	private boolean uploaded;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_variant_id")
	private ProductVariant productVariant;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getAltText() {
		return this.altText;
	}

	public void setAltText(String altText) {
		this.altText = altText;
	}

	public Long getHeight() {
		return this.height;
	}

	public void setHeight(Long height) {
		this.height = height;
	}

	public Long getWidth() {
		return this.width;
	}

	public void setWidth(Long width) {
		this.width = width;
	}

	public String getChecksum() {
		return checksum;
	}

	public void setChecksum(String checksum) {
		this.checksum = checksum;
	}

	public boolean isHidden() {
		return hidden;
	}

	public void setHidden(boolean hidden) {
		this.hidden = hidden;
	}

	public boolean isUploaded() {
		return uploaded;
	}

	public void setUploaded(boolean uploaded) {
		this.uploaded = uploaded;
	}

	public ProductVariant getProductVariant() {
		return productVariant;
	}

	public void setProductVariant(ProductVariant productVariant) {
		this.productVariant = productVariant;
	}

	public Long getImageType() {
		return imageType;
	}

	public void setImageType(Long imageType) {
		this.imageType = imageType;
	}

	@Override
	public String toString() {
		return id == null ? "" : id.toString();
	}
}


