package com.hk.domain.catalog.product;
// Generated 13 Sep, 2012 11:55:47 PM by Hibernate Tools 3.2.4.CR1


import com.hk.domain.user.User;

import javax.persistence.*;
import java.util.Date;

/**
 * UpdatePvPrice generated by hbm2java
 */
@Entity
@Table (name = "update_pv_price")
public class UpdatePvPrice implements java.io.Serializable {


	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column (name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "updated_by")
	private User updatedBy;

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "product_variant_id", nullable = false)
	private ProductVariant productVariant;


	@Column (name = "new_mrp", nullable = false, precision = 10)
	private Double newMrp;


	@Column (name = "new_hkprice", nullable = false, precision = 10)
	private Double newHkprice;

	@Temporal (TemporalType.TIMESTAMP)
	@Column (name = "txn_date", nullable = false, length = 19)
	private Date txnDate;


	@Column (name = "updated", nullable = false, columnDefinition = "tinyint(1) default 0")
	private boolean updated;

	@Temporal (TemporalType.TIMESTAMP)
	@Column (name = "update_date", length = 19)
	private Date updateDate;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(User updatedBy) {
		this.updatedBy = updatedBy;
	}

	public ProductVariant getProductVariant() {
		return this.productVariant;
	}

	public void setProductVariant(ProductVariant productVariant) {
		this.productVariant = productVariant;
	}

	public Double getNewMrp() {
		return this.newMrp;
	}

	public void setNewMrp(Double newMrp) {
		this.newMrp = newMrp;
	}

	public Double getNewHkprice() {
		return this.newHkprice;
	}

	public void setNewHkprice(Double newHkprice) {
		this.newHkprice = newHkprice;
	}

	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	public boolean isUpdated() {
		return this.updated;
	}

	public void setUpdated(boolean updated) {
		this.updated = updated;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Override
	public String toString() {
		return id == null ? "" : id.toString();
	}

}


