package com.hk.domain.catalog.product;
// Generated Feb 7, 2012 4:39:32 PM by Hibernate Tools 3.2.4.CR1


import java.util.Set;
import java.util.TreeSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Sort;
import org.hibernate.annotations.SortType;

/**
 * VariantConfig generated by hbm2java
 */
@Entity
@Table(name = "variant_config")
public class VariantConfig implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;


  @Column(name = "name", nullable = false, length = 45)
  private String name;



  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "variantConfig")
  @Sort(type= SortType.NATURAL)
  private Set<VariantConfigOption> variantConfigOptions = new TreeSet<VariantConfigOption>();

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set<VariantConfigOption> getVariantConfigOptions() {
    return variantConfigOptions;
  }

  public void setVariantConfigOptions(Set<VariantConfigOption> variantConfigOptions) {
    this.variantConfigOptions = variantConfigOptions;
  }
}


