package com.hk.domain.catalog.product;
// Generated Feb 7, 2012 4:39:32 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VariantConfigValues generated by hbm2java
 */
@Entity
@Table(name = "variant_config_values")
public class VariantConfigValues implements java.io.Serializable,Comparable<VariantConfigValues> {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "variant_config_option_id", nullable = false)
  private VariantConfigOption variantConfigOption;

  @Column(name = "value", nullable = false, length = 45)
  private String value;

  @Column(name = "additonal_price", nullable = false, precision = 10)
  private Double additonalPrice;

  @Column(name = "display_order", nullable = false)
  private long displayOrder;

  @Column(name = "cost_price", nullable = false, precision = 10)
  private Double costPrice;

  public long getDisplayOrder() {
    return displayOrder;
  }

  public void setDisplayOrder(long displayOrder) {
    this.displayOrder = displayOrder;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public VariantConfigOption getVariantConfigOption() {
    return this.variantConfigOption;
  }

  public void setVariantConfigOption(VariantConfigOption variantConfigOption) {
    this.variantConfigOption = variantConfigOption;
  }

  public String getValue() {
    return this.value;
  }


  public String getValueWithPrice() {
    if (this.additonalPrice != null && this.additonalPrice > new Double(0)) {
      return new StringBuilder(this.value).append(" + Rs.").append(this.additonalPrice.toString()).toString();
    }
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public Double getAdditonalPrice() {
    return this.additonalPrice;
  }

  public void setAdditonalPrice(Double additonalPrice) {
    this.additonalPrice = additonalPrice;
  }

   public int compareTo(VariantConfigValues o) {
    return ((Long)o.getDisplayOrder()).compareTo(this.displayOrder);
  }

  public Double getCostPrice() {
    return costPrice;
  }

  public void setCostPrice(Double costPrice) {
    this.costPrice = costPrice;
  }
}


