package com.hk.domain.accounting;
// Generated Nov 14, 2011 11:21:33 AM by Hibernate Tools 3.2.4.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.hk.domain.order.ShippingOrder;


/**
 * AccountingInvoice generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "accounting_invoice")
public class AccountingInvoice implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  /**
   * TODO: #warehouse this order reference needs to be replaced by shipping order reference 
   */
 /* @Deprecated
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "order_id")
  private Order order;*/

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "shipping_order_id")
  private ShippingOrder shippingOrder;

  @Column(name = "retail_invoice_id")
  private Long retailInvoiceId;

  @Column(name = "service_invoice_id")
  private Long serviceInvoiceId;

  @Column(name = "b2b_invoice_id")
  private Long b2bInvoiceId;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "invoice_date", nullable = false, length = 19)
  private Date invoiceDate;

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "accountingInvoice")
  private List<InvoiceLineItem> invoiceLineItems = new ArrayList<InvoiceLineItem>();

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  /*@Deprecated
  public Order getOrder() {
    return order;
  }
  
  @Deprecated
  public void setOrder(Order order) {
    this.order = order;
  }*/

  public Long getRetailInvoiceId() {
    return this.retailInvoiceId;
  }

  public void setRetailInvoiceId(Long retailInvoiceId) {
    this.retailInvoiceId = retailInvoiceId;
  }

  public Long getServiceInvoiceId() {
    return serviceInvoiceId;
  }

  public void setServiceInvoiceId(Long serviceInvoiceId) {
    this.serviceInvoiceId = serviceInvoiceId;
  }

  public Long getB2bInvoiceId() {
    return b2bInvoiceId;
  }

  public void setB2bInvoiceId(Long b2bInvoiceId) {
    this.b2bInvoiceId = b2bInvoiceId;
  }

  public Date getInvoiceDate() {
    return this.invoiceDate;
  }

  public void setInvoiceDate(Date invoiceDate) {
    this.invoiceDate = invoiceDate;
  }

  public List<InvoiceLineItem> getInvoiceLineItems() {
    return invoiceLineItems;
  }

  public void setInvoiceLineItems(List<InvoiceLineItem> invoiceLineItems) {
    this.invoiceLineItems = invoiceLineItems;
  }

  public ShippingOrder getShippingOrder() {
    return shippingOrder;
  }

  public void setShippingOrder(ShippingOrder shippingOrder) {
    this.shippingOrder = shippingOrder;
  }
}


