package com.hk.domain.accounting;
// Generated 30 Dec, 2011 7:02:04 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hk.domain.catalog.product.ProductVariant;
import com.hk.domain.core.Tax;
import com.hk.domain.sku.Sku;

/**
 * DebitNoteLineItem generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "debit_note_line_item")
public class DebitNoteLineItem implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "debit_note_id", nullable = false)
  private DebitNote debitNote;

  @Column(name = "qty", nullable = false)
  private Long qty;

  @Column(name = "cost_price", nullable = false, precision = 8)
  private Double costPrice;

  @Column(name = "mrp", nullable = false, precision = 8)
  private Double mrp;

  @Transient
  private ProductVariant productVariant;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "sku_id", nullable = false)
  private Sku sku;

	@Column(name = "remarks")
  private String remarks;

	@ManyToOne (fetch = FetchType.LAZY)
  @JoinColumn (name = "tax_id")
  private Tax tax;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public DebitNote getDebitNote() {
    return this.debitNote;
  }

  public void setDebitNote(DebitNote debitNote) {
    this.debitNote = debitNote;
  }

  public Long getQty() {
    return this.qty;
  }

  public void setQty(Long qty) {
    this.qty = qty;
  }

  public Double getCostPrice() {
    return this.costPrice;
  }

  public void setCostPrice(Double costPrice) {
    this.costPrice = costPrice;
  }

  public Double getMrp() {
    return this.mrp;
  }

  public void setMrp(Double mrp) {
    this.mrp = mrp;
  }

  public ProductVariant getProductVariant() {
    return productVariant;
  }

  public void setProductVariant(ProductVariant productVariant) {
    this.productVariant = productVariant;
  }

  public Sku getSku() {
    return sku;
  }

  public void setSku(Sku sku) {
    this.sku = sku;
  }

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Tax getTax() {
		return tax;
	}

	public void setTax(Tax tax) {
		this.tax = tax;
	}
}


