package com.hk.domain.accounting;
// Generated Oct 5, 2011 4:39:10 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.hk.domain.catalog.product.ProductVariant;
import com.hk.domain.inventory.po.PurchaseOrder;
import com.hk.domain.sku.Sku;

/**
 * PoLineItem generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table (name = "po_line_item", uniqueConstraints = @UniqueConstraint (columnNames = {"purchase_order_id", "sku_id"}))
public class PoLineItem implements java.io.Serializable {


  @Id
  @GeneratedValue (strategy = GenerationType.AUTO)
  @Column (name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne (fetch = FetchType.LAZY)
  @JoinColumn (name = "purchase_order_id", nullable = false)
  private PurchaseOrder purchaseOrder;


  @Column (name = "qty", nullable = false)
  private Long qty;


  @Column (name = "cost_price", precision = 8)
  private Double costPrice;


  @Column (name = "mrp", precision = 8)
  private Double mrp;

  @Transient
  private ProductVariant productVariant;

  @ManyToOne (fetch = FetchType.LAZY)
  @JoinColumn (name = "sku_id", nullable = false)
  private Sku sku;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PurchaseOrder getPurchaseOrder() {
    return this.purchaseOrder;
  }

  public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
    this.purchaseOrder = purchaseOrder;
  }

  public Long getQty() {
    return this.qty;
  }

  public void setQty(Long qty) {
    this.qty = qty;
  }

  public Double getCostPrice() {
    return this.costPrice;
  }

  public void setCostPrice(Double costPrice) {
    this.costPrice = costPrice;
  }

  public Double getMrp() {
    return mrp;
  }

  public void setMrp(Double mrp) {
    this.mrp = mrp;
  }

  public ProductVariant getProductVariant() {
    return productVariant;
  }

  public void setProductVariant(ProductVariant productVariant) {
    this.productVariant = productVariant;
  }

  public Sku getSku() {
    return sku;
  }

  public void setSku(Sku sku) {
    this.sku = sku;
  }


  @Override
  public String toString() {
    return this.id != null ? this.id.toString() : "";
  }
}


