package com.hk.domain.accounting;
// Generated Oct 5, 2011 4:39:10 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.*;

import com.hk.domain.catalog.product.ProductVariant;
import com.hk.domain.inventory.po.PurchaseOrder;
import com.hk.domain.sku.Sku;
import com.hk.domain.inventory.rtv.ExtraInventoryLineItem;

/**
 * PoLineItem generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "po_line_item", uniqueConstraints = @UniqueConstraint(columnNames = {"purchase_order_id", "sku_id"}))
public class PoLineItem implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "purchase_order_id", nullable = false)
	private PurchaseOrder purchaseOrder;

	@Column(name = "qty", nullable = false)
	private Long qty;

	@Column(name = "cost_price", precision = 8)
	private Double costPrice;

	@Column(name = "mrp", precision = 8)
	private Double mrp;

	@Column(name = "taxable_amount")
	private Double taxableAmount;

	@Column(name = "tax_amount")
	private Double taxAmount;

	@Column(name = "surcharge_amount")
	private Double surchargeAmount;

	@Column(name = "payable_amount")
	private Double payableAmount;

	@Column(name = "discount_percent")
	private Double discountPercent;

	@Column(name = "procurement_price")
	private Double procurementPrice;

	@Transient
	private ProductVariant productVariant;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sku_id", nullable = false)
	private Sku sku;

	@Column(name = "received_qty")
	private Long receivedQty;

	@Column(name = "fill_rate")
	private Double fillRate;

  @OneToOne
  @JoinColumn (name = "extra_inventory_line_item_id")
  private ExtraInventoryLineItem extraInventoryLineItem;
  
  @Column(name = "remarks")
  private String remarks;
  
  @Transient
  private boolean firstTimePurchased;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public PurchaseOrder getPurchaseOrder() {
		return this.purchaseOrder;
	}

	public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
		this.purchaseOrder = purchaseOrder;
	}

	public Long getQty() {
		return this.qty;
	}

	public void setQty(Long qty) {
		this.qty = qty;
	}

	public Double getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(Double costPrice) {
		this.costPrice = costPrice;
	}

	public Double getMrp() {
		return mrp;
	}

	public void setMrp(Double mrp) {
		this.mrp = mrp;
	}

	public ProductVariant getProductVariant() {
		return productVariant;
	}

	public void setProductVariant(ProductVariant productVariant) {
		this.productVariant = productVariant;
	}

	public Sku getSku() {
		return sku;
	}

	public void setSku(Sku sku) {
		this.sku = sku;
	}

	public Double getDiscountPercent() {
		return discountPercent;
	}

	public void setDiscountPercent(Double discountPercent) {
		this.discountPercent = discountPercent;
	}

	public Double getTaxableAmount() {
		return taxableAmount;
	}

	public void setTaxableAmount(Double taxableAmount) {
		this.taxableAmount = taxableAmount;
	}

	public Double getTaxAmount() {
		return taxAmount;
	}

	public void setTaxAmount(Double taxAmount) {
		this.taxAmount = taxAmount;
	}

	public Double getSurchargeAmount() {
		return surchargeAmount;
	}

	public void setSurchargeAmount(Double surchargeAmount) {
		this.surchargeAmount = surchargeAmount;
	}

	public Double getPayableAmount() {
		return payableAmount;
	}

	public void setPayableAmount(Double payableAmount) {
		this.payableAmount = payableAmount;
	}

	public Double getProcurementPrice() {
		return procurementPrice;
	}

	public void setProcurementPrice(Double procurementPrice) {
		this.procurementPrice = procurementPrice;
	}

	public Long getReceivedQty() {
		return receivedQty;
	}

	public void setReceivedQty(Long receivedQty) {
		this.receivedQty = receivedQty;
	}

	public Double getFillRate() {
		return fillRate;
	}

	public void setFillRate(Double fillRate) {
		this.fillRate = fillRate;
	}

  public ExtraInventoryLineItem getExtraInventoryLineItem() {
    return extraInventoryLineItem;
  }

  public void setExtraInventoryLineItem(ExtraInventoryLineItem extraInventoryLineItem) {
    this.extraInventoryLineItem = extraInventoryLineItem;
  }
  
  public boolean isFirstTimePurchased() {
	return firstTimePurchased;
  }

  public void setFirstTimePurchased(boolean firstTimePurchased) {
	this.firstTimePurchased = firstTimePurchased;
  }

@Override
	public String toString() {
		return this.id != null ? this.id.toString() : "";
	}

	public String getRemarks() {
		return remarks;
	}
	
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}


