package com.hk.domain.review;
// Generated Jan 7, 2013 2:53:10 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.*;


/**
 * Mail generated by hbm2java
 */
@Entity
@Table(name="mail")
public class Mail  implements java.io.Serializable {


 
    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    @Column(name="id", unique=true, nullable=false)
    private Long id;
 
    
    @Column(name="name", length=45)
    private String name;
 
    
    @Column(name="content")
    private String content;

    @Column(name = "amazon_file_path")
    private String amazonFilePath;

    @Column(name = "subject")
    private String subject;

   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getAmazonFilePath() {
        return amazonFilePath;
    }

    public void setAmazonFilePath(String amazonFileName) {
        this.amazonFilePath = amazonFileName;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Override
    public String toString() {
        return id != null ? id.toString() : "";
    }
}


