package com.hk.domain.review;
// Generated Jan 6, 2013 10:43:34 PM by Hibernate Tools 3.2.4.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductReviewMail generated by hbm2java
 */
@Entity
@Table(name="product_review_mail")
public class ProductReviewMail  implements java.io.Serializable {


 
    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    private Long id;
 
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mail_id", nullable=false)
    private Mail mail;
 
    
    @Column(name="time_window_days")
    private Long timeWindowDays;
 
    
    @Column(name="days_to_review_again")
    private Long daysToReviewAgain;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_dt", length=19)
    private Date createDt;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_dt", nullable=false, length=19)
    private Date updateDt;
 
    
    @Column(name="is_enabled", nullable=false)
    private boolean isEnabled;
 
    
    @Column(name="product_id", nullable=false, length=20)
    private String productId;
 
    
    @Column(name="created_by", nullable=false)
    private Long createdBy;
 
    
    @Column(name="last_updated_by", nullable=false)
    private Long lastUpdatedBy;
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Mail getMail() {
        return this.mail;
    }
    
    public void setMail(Mail mail) {
        this.mail = mail;
    }
    public Long getTimeWindowDays() {
        return this.timeWindowDays;
    }
    
    public void setTimeWindowDays(Long timeWindowDays) {
        this.timeWindowDays = timeWindowDays;
    }
    public Long getDaysToReviewAgain() {
        return this.daysToReviewAgain;
    }
    
    public void setDaysToReviewAgain(Long daysToReviewAgain) {
        this.daysToReviewAgain = daysToReviewAgain;
    }
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }
    public Date getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
    public boolean isIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(boolean isEnabled) {
        this.isEnabled = isEnabled;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Long getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }




}


