package com.hk.domain.review;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hk.domain.user.User;

/**
 * ReviewVote generated by hbm2java
 */
@Entity
@Table (name = "review_vote")
public class ReviewVote implements java.io.Serializable {


  @Id
  @GeneratedValue (strategy = GenerationType.AUTO)

  @Column (name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne (fetch = FetchType.LAZY)
  @JoinColumn (name = "user_id", nullable = false)
  private User user;

  @ManyToOne (fetch = FetchType.LAZY)
  @JoinColumn (name = "user_review_id", nullable = false)
  private UserReview userReview;


  @Column (name = "vote_type", nullable = false)
  private Long voteType;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public User getUser() {
    return this.user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public UserReview getUserReview() {
    return this.userReview;
  }

  public void setUserReview(UserReview userReview) {
    this.userReview = userReview;
  }

  public Long getVoteType() {
    return this.voteType;
  }

  public void setVoteType(Long voteType) {
    this.voteType = voteType;
  }


}


