package com.hk.domain.review;
// Generated Jan 6, 2013 10:43:34 PM by Hibernate Tools 3.2.4.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserReviewMail generated by hbm2java
 */
@Entity
@Table(name="user_review_mail")
public class UserReviewMail  implements java.io.Serializable {


 
    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    private Long id;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="due_date", length=19)
    private Date dueDate;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_dt", length=19)
    private Date createDt;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_dt", nullable=false, length=19)
    private Date updateDt;
 
    
    @Column(name="is_mail_sent")
    private Boolean isMailSent;
 
    
    @Column(name="user_id", nullable=false)
    private Long userId;
 
    
    @Column(name="product_id", nullable=false, length=20)
    private String productId;
 
    
    @Column(name="user_review_id")
    private Long userReviewId;
 
    
    @Column(name="base_order_id", nullable=false)
    private Long baseOrderId;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sent_date", length=19)
    private Date sentDate;
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }
    public Date getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
    public Boolean getIsMailSent() {
        return this.isMailSent;
    }
    
    public void setIsMailSent(Boolean isMailSent) {
        this.isMailSent = isMailSent;
    }
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public Long getUserReviewId() {
        return this.userReviewId;
    }
    
    public void setUserReviewId(Long userReviewId) {
        this.userReviewId = userReviewId;
    }
    public Long getBaseOrderId() {
        return this.baseOrderId;
    }
    
    public void setBaseOrderId(Long baseOrderId) {
        this.baseOrderId = baseOrderId;
    }
    public Date getSentDate() {
        return this.sentDate;
    }
    
    public void setSentDate(Date sentDate) {
        this.sentDate = sentDate;
    }




}


