package com.hk.domain.payment;
// Generated Jan 25, 2012 3:08:29 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PreferredBankGateway generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "preferred_bank_gateway")
public class PreferredBankGateway implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @Column(name = "bank_name", nullable = false, length = 45)
  private String bankName;

  @Column(name = "tpsl_bank_code", length = 45)
  private String tpslBankCode;

  @Column(name = "citrus_bank_code", length = 45)
  private String citrusBankCode;

  @Column(name = "preferred_gateway_id")
  private Long preferredGatewayId;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getBankName() {
    return this.bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public String getTpslBankCode() {
    return this.tpslBankCode;
  }

  public void setTpslBankCode(String tpslBankCode) {
    this.tpslBankCode = tpslBankCode;
  }

  public String getCitrusBankCode() {
    return this.citrusBankCode;
  }

  public void setCitrusBankCode(String citrusBankCode) {
    this.citrusBankCode = citrusBankCode;
  }

  public Long getPreferredGatewayId() {
    return this.preferredGatewayId;
  }

  public void setPreferredGatewayId(Long preferredGatewayId) {
    this.preferredGatewayId = preferredGatewayId;
  }


}


