package com.hk.domain.pk;
// Generated Jan 28, 2012 2:42:31 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransactionFooterId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class TransactionFooterPk  implements java.io.Serializable {


    @Column(name="vch_code", nullable=false)
    private Long vchCode;
 

    @Column(name="s_no", nullable=false)
    private Long sNo;

	public TransactionFooterPk(){
	}

	public TransactionFooterPk(Long vchCode, Long sNo){
		this.vchCode = vchCode;
		this.sNo = sNo;
	} 

    public Long getVchCode() {
        return this.vchCode;
    }
    
    public void setVchCode(Long vchCode) {
        this.vchCode = vchCode;
    }
    public Long getSNo() {
        return this.sNo;
    }
    
    public void setSNo(Long SNo) {
        this.sNo = SNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TransactionFooterPk) ) return false;
		 TransactionFooterPk castOther = ( TransactionFooterPk ) other; 
         
	  return ((this.getVchCode() == castOther.getVchCode()) || (this.getVchCode() != null && castOther.getVchCode() != null && this.getVchCode().equals(castOther.getVchCode())))
		  && ((this.getSNo() == castOther.getSNo()) || (this.getSNo() != null && castOther.getSNo() != null && this.getSNo().equals(castOther.getSNo())));   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVchCode() == null ? 0 : this.getVchCode().hashCode() );
         result = 37 * result + ( getSNo() == null ? 0 : this.getSNo().hashCode() );
         return result;
   }   

  @Override
  public String toString() {
    return vchCode + "," + sNo;
  }



}


