<%@ page import="com.hk.constants.catalog.image.EnumImageSize" %>
<%@ page import="com.hk.constants.core.PermissionConstants" %>
<%@ page import="com.hk.constants.core.RoleConstants" %>
<%@ page import="com.hk.domain.core.Surcharge" %>
<%@ page import="com.hk.domain.core.Tax" %>
<%@ page import="com.hk.pact.dao.MasterDataDao" %>
<%@ page import="com.hk.pact.dao.TaxDao" %>
<%@ page import="com.hk.service.ServiceLocatorFactory" %>
<%@ page import="com.hk.web.HealthkartResponse" %>
<%@ page import="java.util.List" %>
<%@ page import="com.hk.domain.core.PurchaseFormType" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/includes/_taglibInclude.jsp" %>
<%@ page import="com.hk.admin.util.TaxUtil" %>
<s:useActionBean beanclass="com.hk.web.action.admin.inventory.PurchaseInvoiceAction" var="pia"/>
<s:layout-render name="/layouts/defaultAdmin.jsp" pageTitle="Purchase Invoice">

<%
	TaxDao taxDao = ServiceLocatorFactory.getService(TaxDao.class);
	List<Tax> taxList = taxDao.getLocalTaxList();
	pageContext.setAttribute("taxList", taxList);

	MasterDataDao masterDataDao = (MasterDataDao) ServiceLocatorFactory.getService(MasterDataDao.class);
	List<PurchaseFormType> purchaseFormTypes = masterDataDao.getPurchaseInvoiceFormTypes();
	pageContext.setAttribute("purchaseFormTypes", purchaseFormTypes);
%>


<s:layout-component name="htmlHead">
<link href="${pageContext.request.contextPath}/css/calendar-blue.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery.dynDateTime.pack.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/js/calendar-en.js"></script>
<jsp:include page="/includes/_js_labelifyDynDateMashup.jsp"/>
<script type="text/javascript">
	$(document).ready(function() {
		$('#save-button').click(function(){
			var reconciled = $('#reconciled').val();
			var status = $('#status').val();
			var paymentDate = $('#payment-date').val();
			if (paymentDate== "yyyy-mm-dd" ||  paymentDate == null || paymentDate == "") {
				if (reconciled && status == 10) {
					var confirm_action = confirm("PI is reconciled but status is Generated. Are you sure you don't want to change the status to Payment Pending?");
					if (!confirm_action) {
						event.preventDefault();
					}
				}
			}

		});
	});
</script>
</s:layout-component>
<s:layout-component name="heading">
	Update payment and status for PI # ${pia.purchaseInvoice.id}
</s:layout-component>
<s:layout-component name="content">
<div style="display: none;">
	<s:link beanclass="com.hk.web.action.admin.inventory.PurchaseInvoiceAction" id="pvInfoLink"
	        event="getPVDetails"></s:link>
</div>

<s:form beanclass="com.hk.web.action.admin.inventory.PurchaseInvoiceAction">
<s:hidden name="purchaseInvoice" value="${pia.purchaseInvoice}"/>
<table>
	<tr><td>Warehouse :</td>
		<td><strong>${pia.purchaseInvoice.warehouse.city}</strong></td>
	</tr>
	<tr>
		<td>Supplier Name</td>
		<td>${pia.purchaseInvoice.supplier.name}</td>

		<td>Supplier State</td>
		<td id="supplierState">${pia.purchaseInvoice.supplier.state}</td>

		<td>Tax</td>
		<td>
			<c:choose>
				<c:when test="${pia.purchaseInvoice.supplier.state == pia.purchaseInvoice.warehouse.state}">
					<label class="state">NON-CST</label>
				</c:when>
				<c:otherwise>
					<label class="state">CST</label>
				</c:otherwise>
			</c:choose>
		</td>

	</tr>

	<tr>
		<td>Invoice Date</td>
		<td>
			${pia.purchaseInvoice.invoiceDate}
		</td>
		<td>Invoice Number</td>
		<td>${pia.purchaseInvoice.invoiceNumber}</td>
		<td>GRN Date</td>
		<td>${pia.grnDate}</td>

	</tr>

	<tr>
		<td>Credit Days</td>
		<td>${pia.purchaseInvoice.supplier.creditDays}</td>
		<td>Adv .Payment</td>
		<td>
			<c:set var="advPayment" value="0"/>
			<c:forEach items="${pia.purchaseInvoice.goodsReceivedNotes}" var="grn">
				<c:set var="advPayment" value="${grn.purchaseOrder.advPayment + advPayment}"/>
				${advPayment}
			</c:forEach>

		</td>
		<td>Payable</td>
		<td><fmt:formatNumber value="${pia.purchaseInvoice.finalPayableAmount - advPayment}" type="currency" currencySymbol=" " maxFractionDigits="0"/></td>

	</tr>

	<tr>
		<td>Est. Payment Date</td>
		<td><fmt:formatDate value="${pia.purchaseInvoice.estPaymentDate}"/></td>
		<td>Payment Date</td>
		<td>
			<s:text class="date_input" formatPattern="yyyy-MM-dd" name="purchaseInvoice.paymentDate" id="payment-date"/></td>
		<td>Payment Details<br/><span class="sml gry">(eg. Cheque no.)</span></td>
		<td><s:textarea name="purchaseInvoice.paymentDetails" style="height:50px;"/></td>
	</tr>
	<tr>
		<td>Generated By</td>
		<td>
				${pia.purchaseInvoice.createdBy.name}</td>
		<td>Reconciled</td>
		<td>
			<c:choose>
              <c:when test="${pia.purchaseInvoice.reconciled}">
                Yes &#10004;
              </c:when>
              <c:otherwise>
                No
              </c:otherwise>
            </c:choose>
		</td>
		<td>Reconcilation Date</td>
		<c:choose>
			<c:when test="${hk:isNotBlank(pia.purchaseInvoice.reconcilationDate)}">
				<td>${pia.purchaseInvoice.reconcilationDate}</td>
			</c:when>
			<c:otherwise>
				<td></td>
			</c:otherwise>
		</c:choose>

	</tr>

	<tr>
		<td>Form Type</td>
		<td>
			${pia.purchaseInvoice.purchaseFormType}
		</td>
		<td>Status</td>
		<td><s:select name="purchaseInvoice.purchaseInvoiceStatus"  id="status"
		              value="${pia.purchaseInvoice.purchaseInvoiceStatus.id}">
			<hk:master-data-collection service="<%=MasterDataDao.class%>" serviceProperty="purchaseInvoiceStatusList"
			                           value="id" label="name"/>
		</s:select></td>
		<td>Route Permit Number</td>
		<td>${pia.purchaseInvoice.routePermitNumber}</td>
		<td></td>
		<td></td>
	</tr>
</table>

<br/>

	<s:submit name="updateStatusAndPaymentDetails" value="Save" id="save-button"/>
</s:form>

</s:layout-component>

</s:layout-render>
