package com.hk.domain.inventory.crossDomain;
// Generated 21 May, 2013 4:09:07 PM by Hibernate Tools 3.2.4.CR1


import com.hk.domain.user.User;
import com.hk.domain.inventory.po.PurchaseOrder;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InventoryBarcodeMap generated by hbm2java
 */
@Entity
@Table(name = "inventory_barcode_map")
public class InventoryBarcodeMap implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = false)
  private User user;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "po_id", nullable = false)
  private PurchaseOrder purchaseOrder;


  @Column(name = "status", nullable = false, length = 45)
  private String status;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "create_date", nullable = false, length = 19)
  private Date createDate;

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "inventoryBarcodeMap")
  private Set<InventoryBarcodeMapItem> inventoryBarcodeMapItems = new HashSet<InventoryBarcodeMapItem>(0);

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public User getUser() {
    return this.user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public PurchaseOrder getPurchaseOrder() {
    return purchaseOrder;
  }

  public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
    this.purchaseOrder = purchaseOrder;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  public Set<InventoryBarcodeMapItem> getInventoryBarcodeMapItems() {
    return this.inventoryBarcodeMapItems;
  }

  public void setInventoryBarcodeMapItems(Set<InventoryBarcodeMapItem> inventoryBarcodeMapItems) {
    this.inventoryBarcodeMapItems = inventoryBarcodeMapItems;
  }


}


