package com.hk.domain.search;
// Generated 15 May, 2013 6:33:15 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.*;

/**
 * SearchLog generated by hbm2java
 */
@Entity
@Table(name = "search_log")
public class SearchLog implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @Column(name = "traffic_tracking_id", nullable = false, length = 200)
  private Long trafficTrackingId;

  @Column(name = "keyword", nullable = false, length = 200)
  private String keyword;


  @Column(name = "results", nullable = false)
  private Long results;

  @Column(name = "category", nullable = false, length = 200)
  private String category;

  @Column(name = "first_click_pos", length = 45)
  private String firstClickPos;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Long getTrafficTrackingId() {
    return trafficTrackingId;
  }

  public void setTrafficTrackingId(Long trafficTrackingId) {
    this.trafficTrackingId = trafficTrackingId;
  }

  public String getKeyword() {
    return this.keyword;
  }

  public void setKeyword(String keyword) {
    this.keyword = keyword;
  }

  public Long getResults() {
    return this.results;
  }

  public void setResults(Long results) {
    this.results = results;
  }

  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public String getFirstClickPos() {
    return firstClickPos;
  }

  public void setFirstClickPos(String firstClickPos) {
    this.firstClickPos = firstClickPos;
  }
}


