package com.hk.domain.marketing;
// Generated 23 Oct, 2010 1:16:20 PM by Hibernate Tools 3.2.4.CR1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FbcouponCampaign generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "fbcoupon_campaign")
public class FbcouponCampaign implements java.io.Serializable {

  @Id
  @Column(name = "code", unique = true, nullable = false, length = 45)
  private String code;

  @Column(name = "name", nullable = false, length = 45)
  private String name;

  @Column(name = "share_url", length = 200)
  private String shareUrl;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "create_date", nullable = false, length = 19)
  private Date createDate;

  public String getCode() {
    return this.code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getShareUrl() {
    return this.shareUrl;
  }

  public void setShareUrl(String shareUrl) {
    this.shareUrl = shareUrl;
  }

  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  @Override
  public String toString() {
    return code;
  }
}


