package com.hk.domain.marketing;
// Generated Dec 21, 2011 2:56:57 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GoogleBannedWord generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "google_banned_word")
public class GoogleBannedWord implements java.io.Serializable {


  @Id
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @Column(name = "banned_word", length = 100)
  private String bannedWord;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getBannedWord() {
    return this.bannedWord;
  }

  public void setBannedWord(String bannedWord) {
    this.bannedWord = bannedWord;
  }


}


