package com.hk.domain.marketing;
// Generated Mar 5, 2012 4:11:02 PM by Hibernate Tools 3.2.4.CR1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.hk.domain.catalog.category.Category;

/**
 * MarketingExpense generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "marketing_expense", uniqueConstraints = @UniqueConstraint(columnNames = {"date", "ad_networks_id", "category"}))
public class MarketingExpense implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;


  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "category", nullable = false)
  private Category category;


  @Column(name = "impression")
  private Long impression;


  @Column(name = "click")
  private Long click;


  @Column(name = "amount_spend", precision = 10)
  private Double amountSpend;


  @Column(name = "conversion")
  private Long conversion;


  @Column(name = "cost_of_conversion", precision = 10)
  private Double costOfConversion;

  @Temporal(TemporalType.DATE)
  @Column(name = "date", length = 10)
  private Date date;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "ad_networks_id", nullable = false)
  private AdNetworks adNetworks;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Category getCategory() {
    return this.category;
  }

  public void setCategory(Category category) {
    this.category = category;
  }

  public Long getImpression() {
    return this.impression;
  }

  public void setImpression(Long impression) {
    this.impression = impression;
  }

  public Long getClick() {
    return this.click;
  }

  public void setClick(Long click) {
    this.click = click;
  }

  public Double getAmountSpend() {
    return this.amountSpend;
  }

  public void setAmountSpend(Double amountSpend) {
    this.amountSpend = amountSpend;
  }

  public Long getConversion() {
    return this.conversion;
  }

  public void setConversion(Long conversion) {
    this.conversion = conversion;
  }

  public Double getCostOfConversion() {
    return this.costOfConversion;
  }

  public void setCostOfConversion(Double costOfConversion) {
    this.costOfConversion = costOfConversion;
  }

  public Date getDate() {
    return this.date;
  }

  public void setDate(Date date) {
    this.date = date;
  }

  public AdNetworks getAdNetworks() {
    return this.adNetworks;
  }

  public void setAdNetworks(AdNetworks adNetworks) {
    this.adNetworks = adNetworks;
  }


}


