package com.hk.domain.marketing;


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductReferrer generated by hbm2java
 */
@Entity
@Table(name="product_referrer")
public class ProductReferrer  implements java.io.Serializable {
 
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    private Long id;
 
    
    @Column(name="name", nullable=false, length=45)
    private String name;
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
    return id == null ? "" : id.toString();
  }

}


