package com.hk.domain.email;

// Generated 28 Sep, 2011 8:19:31 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.AUTO;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.hk.domain.core.EmailType;

/**
 * EmailCampaign generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "email_campaign")
public class EmailCampaign implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @Column(name = "name", nullable = false, length = 80)
  private String name;

  @Column(name = "template", length = 80)
  private String template;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "create_date", nullable = false, length = 19)
  private Date createDate;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "start_date", length = 19)
  private Date startDate;

  @Column(name = "min_day_gap", nullable = false)
  private Long minDayGap;

  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "email_type_id")
  private EmailType emailType;

  @Column(name = "sent_count", nullable = true)
  private Long sentCount;

  @Column(name = "html_path")
  private String htmlPath;

  @Column(name = "subject")
  private String subject;

  @Column(name = "template_ftl")
  private String templateFtl;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getTemplate() {
    return this.template;
  }

  public void setTemplate(String template) {
    this.template = template;
  }

  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  public Date getStartDate() {
    return this.startDate;
  }

  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  public Long getMinDayGap() {
    return this.minDayGap;
  }

  public void setMinDayGap(Long minDayGap) {
    this.minDayGap = minDayGap;
  }

  public EmailType getEmailType() {
    return emailType;
  }

  public void setEmailType(EmailType emailType) {
    this.emailType = emailType;
  }

  public Long getSentCount() {
    return sentCount;
  }

  public void setSentCount(Long sentCount) {
    this.sentCount = sentCount;
  }

  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public String getTemplateFtl() {
    return templateFtl;
  }

  public void setTemplateFtl(String templateFtl) {
    this.templateFtl = templateFtl;
  }

  public String getHtmlPath() {
    return htmlPath;
  }

  public void setHtmlPath(String htmlPath) {
    this.htmlPath = htmlPath;
  }

  @Override
  public String toString() {
    return id == null ? "" : id.toString();
  }

}
