package com.hk.domain.email;


import com.hk.domain.user.User;

import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;
import java.util.Date;

/**
 * EmailRecepient generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "email_recepient")
public class EmailRecepient implements java.io.Serializable {

  @Id @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @Column(name = "email", nullable = false, length = 100)
  private String email;

  @Column(name = "subscribed", nullable = false)
  private boolean subscribed;

  @Column(name = "name", length = 45)
  private String name;

  @Column(name = "bounce")
  private Boolean bounce;

  @Column(name = "invalid")
  private Boolean invalid;

  @Column(name = "email_count")
  private Long emailCount;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "last_email_date", length = 19)
  private Date lastEmailDate;

  @Column(name = "unsubscribe_token", length = 45)
  private String unsubscribeToken;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = true)
  private User user;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false)
	private Date createDate = new Date();
	
  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public boolean isSubscribed() {
    return subscribed;
  }

  public void setSubscribed(boolean subscribed) {
    this.subscribed = subscribed;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Boolean isBounce() {
    return bounce;
  }

  public void setBounce(Boolean bounce) {
    this.bounce = bounce;
  }

  public Boolean isInvalid() {
    return invalid;
  }

  public void setInvalid(Boolean invalid) {
    this.invalid = invalid;
  }

  public Long getEmailCount() {
    return emailCount;
  }

  public void setEmailCount(Long emailCount) {
    this.emailCount = emailCount;
  }

  public Date getLastEmailDate() {
    return lastEmailDate;
  }

  public void setLastEmailDate(Date lastEmailDate) {
    this.lastEmailDate = lastEmailDate;
  }

  public String getUnsubscribeToken() {
    return unsubscribeToken;
  }

  public void setUnsubscribeToken(String unsubscribeToken) {
    this.unsubscribeToken = unsubscribeToken;
  }

  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public boolean isEmailAllowed() {
    return !isBounce() && !isInvalid() && isSubscribed();
  }

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}


