package com.hk.domain.inventory.creditNote;
// Generated 13 May, 2013 6:34:46 PM by Hibernate Tools 3.2.4.CR1


import com.hk.domain.user.User;
import com.hk.domain.warehouse.Warehouse;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CreditNote generated by hbm2java
 */
@Entity
@Table(name = "credit_note")
public class CreditNote implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = false)
  private User user;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "created_by", nullable = false)
  private User createdBy;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "credit_note_status_id", nullable = false)
  private CreditNoteStatus creditNoteStatus;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "warehouse_id", nullable = false)
  private Warehouse warehouse;


  @Column(name = "is_user_credited", nullable = false)
  private boolean userCredited;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "create_dt", nullable = false, length = 19)
  private Date createDt;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "update_dt", nullable = false, length = 19)
  private Date updateDt;


  @Column(name = "remarks", length = 200)
  private String remarks;

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "creditNote")
  private Set<CreditNoteLineItem> creditNoteLineItems = new HashSet<CreditNoteLineItem>(0);

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public User getCreatedBy() {
    return this.createdBy;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public CreditNoteStatus getCreditNoteStatus() {
    return this.creditNoteStatus;
  }

  public void setCreditNoteStatus(CreditNoteStatus creditNoteStatus) {
    this.creditNoteStatus = creditNoteStatus;
  }

  public Warehouse getWarehouse() {
    return this.warehouse;
  }

  public void setWarehouse(Warehouse warehouse) {
    this.warehouse = warehouse;
  }

  public boolean isUserCredited() {
    return userCredited;
  }

  public boolean getUserCredited() {
    return userCredited;
  }

  public void setUserCredited(boolean userCredited) {
    this.userCredited = userCredited;
  }

  public Date getCreateDt() {
    return this.createDt;
  }

  public void setCreateDt(Date createDt) {
    this.createDt = createDt;
  }

  public Date getUpdateDt() {
    return this.updateDt;
  }

  public void setUpdateDt(Date updateDt) {
    this.updateDt = updateDt;
  }

  public String getRemarks() {
    return this.remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  public Set<CreditNoteLineItem> getCreditNoteLineItems() {
    return this.creditNoteLineItems;
  }

  public void setCreditNoteLineItems(Set<CreditNoteLineItem> creditNoteLineItems) {
    this.creditNoteLineItems = creditNoteLineItems;
  }


}


