package com.hk.domain.inventory.creditNote;
// Generated 13 May, 2013 6:34:46 PM by Hibernate Tools 3.2.4.CR1


import com.hk.domain.core.Tax;
import com.hk.domain.sku.Sku;

import javax.persistence.*;

/**
 * CreditNoteLineItem generated by hbm2java
 */
@Entity
@Table(name = "credit_note_line_item")
public class CreditNoteLineItem implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "credit_note_id", nullable = false)
  private CreditNote creditNote;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "sku_id", nullable = false)
  private Sku sku;


  @Column(name = "qty", nullable = false)
  private Long qty;


  @Column(name = "cost_price", nullable = false, precision = 8)
  private Double costPrice;


  @Column(name = "mrp", nullable = false, precision = 8)
  private Double mrp;


  @Column(name = "remarks", length = 65535)
  private String remarks;

	@ManyToOne (fetch = FetchType.LAZY)
  @JoinColumn (name = "tax_id")
  private Tax tax;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public CreditNote getCreditNote() {
    return this.creditNote;
  }

  public void setCreditNote(CreditNote creditNote) {
    this.creditNote = creditNote;
  }

  public Sku getSku() {
    return this.sku;
  }

  public void setSku(Sku sku) {
    this.sku = sku;
  }

  public Long getQty() {
    return this.qty;
  }

  public void setQty(Long qty) {
    this.qty = qty;
  }

  public Double getCostPrice() {
    return this.costPrice;
  }

  public void setCostPrice(Double costPrice) {
    this.costPrice = costPrice;
  }

  public Double getMrp() {
    return this.mrp;
  }

  public void setMrp(Double mrp) {
    this.mrp = mrp;
  }

  public String getRemarks() {
    return this.remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

	public Tax getTax() {
		return tax;
	}

	public void setTax(Tax tax) {
		this.tax = tax;
	}
}


