package com.hk.domain.coupon;
// Generated 25 Mar, 2011 11:57:39 AM by Hibernate Tools 3.2.4.CR1


import com.hk.domain.offer.Offer;
import com.hk.domain.user.User;
import org.joda.time.DateTime;

import javax.persistence.*;
import java.util.Date;

/**
 * Coupon generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "coupon", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Coupon implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offer_id", nullable = false)
	private Offer offer;

	@Column(name = "code", unique = true, nullable = false, length = 20)
	private String code;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	private Date endDate;

	@Column(name = "allowed_times")
	private Long allowedTimes;

	@Column(name = "already_used")
	private Long alreadyUsed;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "referrer_user_id", nullable = true)
	private User referrerUser;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_type_id", nullable = true)
	private CouponType couponType;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 19)
	private Date createDate = new Date();

	@Column(name = "repetitive_usage", nullable = false)
	private Boolean repetitiveUsage;

	@Column(name = "complimentary_coupon", length = 20)
	private String complimentaryCoupon;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Offer getOffer() {
		return this.offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Long getAllowedTimes() {
		return this.allowedTimes;
	}

	public void setAllowedTimes(Long allowedTimes) {
		this.allowedTimes = allowedTimes;
	}

	public Long getAlreadyUsed() {
		return this.alreadyUsed;
	}

	public void setAlreadyUsed(Long alreadyUsed) {
		this.alreadyUsed = alreadyUsed;
	}

	public User getReferrerUser() {
		return referrerUser;
	}

	public void setReferrerUser(User referrerUser) {
		this.referrerUser = referrerUser;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public boolean isValid() {
		return !(endDate != null && new DateTime(endDate).isBeforeNow()) && !(allowedTimes != null && allowedTimes.compareTo(alreadyUsed) <= 0);
	}

	public Boolean isRepetitiveUsage() {
		return repetitiveUsage;
	}

	public Boolean getRepetitiveUsage() {
		return repetitiveUsage;
	}

	public void setRepetitiveUsage(Boolean repetitiveUsage) {
		this.repetitiveUsage = repetitiveUsage;
	}

	public String getComplimentaryCoupon() {
		return complimentaryCoupon;
	}

	public void setComplimentaryCoupon(String complimentaryCoupon) {
		this.complimentaryCoupon = complimentaryCoupon;
	}

	public CouponType getCouponType() {
		return couponType;
	}

	public void setCouponType(CouponType couponType) {
		this.couponType = couponType;
	}
}


