package com.hk.domain.coupon;
// Generated 23 Oct, 2010 1:16:20 PM by Hibernate Tools 3.2.4.CR1



import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.hk.domain.marketing.FbcouponCampaign;
import com.hk.domain.pk.FbcouponUserCampaignPk;

/**
 * FbcouponUserCampaign generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "fbcoupon_user_campaign")
public class FbcouponUserCampaign implements java.io.Serializable {

  @EmbeddedId
  @AttributeOverrides({
      @AttributeOverride(name = "fbcouponUserId", column = @Column(name = "fbcoupon_user_id", nullable = false)),
      @AttributeOverride(name = "fbcouponCampaignCode", column = @Column(name = "fbcoupon_campaign_code", nullable = false, length = 45))})
  private FbcouponUserCampaignPk pk;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "fbcoupon_campaign_code", nullable = false, insertable = false, updatable = false)
  private FbcouponCampaign fbcouponCampaign;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "fbcoupon_user_id", nullable = false, insertable = false, updatable = false)
  private FbcouponUser fbcouponUser;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "fbcoupon_coupon_id", nullable = false)
  private FbcouponCoupon fbcouponCoupon;

  @Column(name = "shared", nullable = false)
  private Boolean shared;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "create_date", nullable = false, length = 19)
  private Date createDate;

  public FbcouponUserCampaignPk getId() {
    return this.pk;
  }

  public void setId(FbcouponUserCampaignPk pk) {
    this.pk = pk;
  }

  public void setId(Long fbUid, String couponCode) {
    this.pk = new FbcouponUserCampaignPk(fbUid, couponCode);
  }

  public FbcouponCampaign getFbcouponCampaign() {
    return this.fbcouponCampaign;
  }

  public void setFbcouponCampaign(FbcouponCampaign fbcouponCampaign) {
    this.fbcouponCampaign = fbcouponCampaign;
  }

  public FbcouponCoupon getFbcouponCoupon() {
    return this.fbcouponCoupon;
  }

  public void setFbcouponCoupon(FbcouponCoupon fbcouponCoupon) {
    this.fbcouponCoupon = fbcouponCoupon;
  }

  public FbcouponUser getFbcouponUser() {
    return this.fbcouponUser;
  }

  public void setFbcouponUser(FbcouponUser fbcouponUser) {
    this.fbcouponUser = fbcouponUser;
  }

  public Boolean getShared() {
    return this.shared;
  }

  public void setShared(Boolean shared) {
    this.shared = shared;
  }

  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }
}


