package com.hk.domain.coupon;
// Generated 23 Oct, 2010 1:16:20 PM by Hibernate Tools 3.2.4.CR1


import static javax.persistence.GenerationType.AUTO;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.hk.domain.marketing.FbcouponCampaign;

/**
 * FbcouponCoupon generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "fbcoupon_coupon")
public class FbcouponCoupon implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "fbcoupon_campaign_code", nullable = false)
  private FbcouponCampaign fbcouponCampaign;

  @Column(name = "coupon", nullable = false, length = 45)
  private String coupon;

  @Column(name = "bonus_coupon", length = 45)
  private String bonusCoupon;

  @Column(name = "coupon_use_count", nullable = false)
  private Long couponUseCount;

  @Column(name = "bonus_coupon_use_count", nullable = false)
  private Long bonusCouponUseCount;

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "fbcouponCoupon")
  private Set<FbcouponUserCampaign> fbcouponUserCampaigns = new HashSet<FbcouponUserCampaign>(0);

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "create_date", nullable = false, length = 19)
  private Date createDate;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public FbcouponCampaign getFbcouponCampaign() {
    return this.fbcouponCampaign;
  }

  public void setFbcouponCampaign(FbcouponCampaign fbcouponCampaign) {
    this.fbcouponCampaign = fbcouponCampaign;
  }

  public String getCoupon() {
    return this.coupon;
  }

  public void setCoupon(String coupon) {
    this.coupon = coupon;
  }

  public String getBonusCoupon() {
    return this.bonusCoupon;
  }

  public void setBonusCoupon(String bonusCoupon) {
    this.bonusCoupon = bonusCoupon;
  }

  public Long getCouponUseCount() {
    return this.couponUseCount;
  }

  public void setCouponUseCount(Long couponUseCount) {
    this.couponUseCount = couponUseCount;
  }

  public Long getBonusCouponUseCount() {
    return this.bonusCouponUseCount;
  }

  public void setBonusCouponUseCount(Long bonusCouponUseCount) {
    this.bonusCouponUseCount = bonusCouponUseCount;
  }

  public Set<FbcouponUserCampaign> getFbcouponUserCampaigns() {
    return this.fbcouponUserCampaigns;
  }

  public void setFbcouponUserCampaigns(Set<FbcouponUserCampaign> fbcouponUserCampaigns) {
    this.fbcouponUserCampaigns = fbcouponUserCampaigns;
  }

  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }
}


