package com.hk.domain.amazon;
// Generated Dec 23, 2011 1:27:52 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hk.domain.catalog.product.ProductVariant;

/**
 * AmazonFeed generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "amazon_feed")
public class AmazonFeed implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "product_variant_id")
  private ProductVariant productVariant;

  @Column(name = "title", length = 500)
  private String title;

  @Column(name = "amazon_browse_node", length = 45)
  private String amazonBrowseNode;

  @Column(name = "gender")
  private String gender;

  @Column(name = "batteries_included")
  private String batteriesIncluded;

  @Column(name = "warranty")
  private String warranty;

  @Column(name = "item_package_quantity")
  private Long itemPackageQuantity;

  @Column(name = "description")
  private String description;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ProductVariant getProductVariant() {
    return productVariant;
  }

  public void setProductVariant(ProductVariant productVariant) {
    this.productVariant = productVariant;
  }

  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getAmazonBrowseNode() {
    return this.amazonBrowseNode;
  }

  public void setAmazonBrowseNode(String amazonBrowseNode) {
    this.amazonBrowseNode = amazonBrowseNode;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public String getBatteriesIncluded() {
    return batteriesIncluded;
  }

  public void setBatteriesIncluded(String batteriesIncluded) {
    this.batteriesIncluded = batteriesIncluded;
  }

  public String getWarranty() {
    return warranty;
  }

  public void setWarranty(String warranty) {
    this.warranty = warranty;
  }

  public Long getItemPackageQuantity() {
    return itemPackageQuantity;
  }

  public void setItemPackageQuantity(Long itemPackageQuantity) {
    this.itemPackageQuantity = itemPackageQuantity;
  }
}


