package com.hk.domain.content;
// Generated 8 Jun, 2011 3:26:03 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SeoData generated by hbm2java
 */
@Entity
@Table(name = "seo_data")
public class SeoData implements java.io.Serializable {


  @Id
  @Column(name = "id", unique = true, nullable = false, length = 45)
  private String id;

  @Column(name = "h1", length = 250)
  private String h1;

  @Column(name = "title", length = 250)
  private String title;

  @Column(name = "meta_keyword", length = 65535)
  private String metaKeyword;

  @Column(name = "meta_description", length = 65535)
  private String metaDescription;

  @Column(name = "description", length = 65535)
  private String description;

  @Column(name = "description_title", length = 250)
  private String descriptionTitle;

  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getH1() {
    return this.h1;
  }

  public void setH1(String h1) {
    this.h1 = h1;
  }

  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getMetaKeyword() {
    return this.metaKeyword;
  }

  public void setMetaKeyword(String metaKeyword) {
    this.metaKeyword = metaKeyword;
  }

  public String getMetaDescription() {
    return this.metaDescription;
  }

  public void setMetaDescription(String metaDescription) {
    this.metaDescription = metaDescription;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getDescriptionTitle() {
    return descriptionTitle;
  }

  public void setDescriptionTitle(String descriptionTitle) {
    this.descriptionTitle = descriptionTitle;
  }
}


