package com.hk.domain.offer;
// Generated 25 Mar, 2011 11:57:39 AM by Hibernate Tools 3.2.4.CR1


import java.util.*;

import javax.persistence.*;

import com.hk.domain.user.Role;

/**
 * Offer generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "offer")
public class Offer implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "offer_trigger_id")
  private OfferTrigger offerTrigger;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "offer_action_id", nullable = false)
  private OfferAction offerAction;

  @Column(name = "description", length = 200)
  private String description;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "start_date", nullable = false, length = 19)
  private Date startDate;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "end_date", length = 19)
  private Date endDate;

  @Column(name = "exclude_trigger_products", nullable = false)
  private boolean excludeTriggerProducts;

  @Column(name = "offer_identifier", nullable = true, length = 10)
  private String offerIdentifier;

  @Column(name = "complimentary_coupon_description", nullable = true)
  private String complimentaryCouponDescription;

  @Column(name = "terms", nullable = true)
  private String terms;

	@Column(name = "payment_type", nullable = true)
  private Long paymentType;

  @Column(name = "show_promptly", nullable = false)
  private boolean showPromptly;

  @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
  @JoinTable(name = "offer_has_role",
      joinColumns = {@JoinColumn(name = "offer_id", nullable = false, updatable = false)},
      inverseJoinColumns = {@JoinColumn(name = "role_name", nullable = false, updatable = false)}
  )
  private Set<Role> roles = new HashSet<Role>();

	@OneToMany (cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "offer")
	private List<OfferEmailDomain> offerEmailDomains = new ArrayList<OfferEmailDomain>(0);

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OfferTrigger getOfferTrigger() {
    return this.offerTrigger;
  }

  public void setOfferTrigger(OfferTrigger offerTrigger) {
    this.offerTrigger = offerTrigger;
  }

  public OfferAction getOfferAction() {
    return this.offerAction;
  }

  public void setOfferAction(OfferAction offerAction) {
    this.offerAction = offerAction;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Date getStartDate() {
    return this.startDate;
  }

  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  public Date getEndDate() {
    return this.endDate;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  public boolean isExcludeTriggerProducts() {
    return excludeTriggerProducts;
  }

  public void setExcludeTriggerProducts(boolean excludeTriggerProducts) {
    this.excludeTriggerProducts = excludeTriggerProducts;
  }

  public String getOfferIdentifier() {
    return offerIdentifier;
  }

  public void setOfferIdentifier(String offerIdentifier) {
    this.offerIdentifier = offerIdentifier;
  }

  public Set<Role> getRoles() {
    return roles;
  }

  public void setRoles(Set<Role> roles) {
    this.roles = roles;
  }

  public String getComplimentaryCouponDescription() {
    return complimentaryCouponDescription;
  }

  public void setComplimentaryCouponDescription(String complimentaryCouponDescription) {
    this.complimentaryCouponDescription = complimentaryCouponDescription;
  }

  public String getTerms() {
    return terms;
  }

  public void setTerms(String terms) {
    this.terms = terms;
  }

	public Long getPaymentType() {
		return paymentType;
	}

	public void setPaymentType(Long paymentType) {
		this.paymentType = paymentType;
	}

	public List<OfferEmailDomain> getOfferEmailDomains() {
		return offerEmailDomains;
	}

	public void setOfferEmailDomains(List<OfferEmailDomain> offerEmailDomains) {
		this.offerEmailDomains = offerEmailDomains;
	}

  public boolean isShowPromptly() {
    return showPromptly;
  }

  public boolean getShowPromptly() {
    return showPromptly;
  }

  public void setShowPromptly(boolean showPromptly) {
    this.showPromptly = showPromptly;
  }

  @Override
  public String toString() {
    return id == null ? "" : id.toString();
  }

}


