package com.hk.domain.offer;
// Generated 25 Mar, 2011 11:57:39 AM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hk.domain.catalog.product.ProductGroup;
import com.hk.domain.catalog.product.ProductVariant;

import java.util.Date;

/**
 * OfferAction generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "offer_action")
public class OfferAction implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "product_group_id")
  private ProductGroup productGroup;

  @Column(name = "description", nullable = false, length = 200)
  private String description;

  @Column(name = "discount_percent_on_hk_price")
  private Double discountPercentOnHkPrice;

  @Column(name = "discount_percent_on_marked_price")
  private Double discountPercentOnMarkedPrice;

  @Column(name = "qty")
  private Long qty;

  @Column(name = "order_level_discount_amount")
  private Double orderLevelDiscountAmount;

  @Column(name = "discount_percent_on_shipping")
  private Double discountPercentOnShipping;

  @Column(name = "is_cashback")
  private Boolean isCashback;

  @Column(name = "reward_point_cashback_limit")
  private Double rewardPointCashbackLimit;

  @Column(name = "reward_point_discount_percent")
  private Double rewardPointDiscountPercent;

  @Column (name = "reward_point_expiry_date")
  private Date rewardPointExpiryDate;

	@Column (name = "reward_point_redeem_within_days")
  private Integer rewardPointRedeemWithinDays;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "free_variant_id")
  private ProductVariant freeVariant;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ProductGroup getProductGroup() {
    return this.productGroup;
  }

  public void setProductGroup(ProductGroup productGroup) {
    this.productGroup = productGroup;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Double getOrderLevelDiscountAmount() {
    return this.orderLevelDiscountAmount;
  }

  public void setOrderLevelDiscountAmount(Double orderLevelDiscountAmount) {
    this.orderLevelDiscountAmount = orderLevelDiscountAmount;
  }

  public Double getDiscountPercentOnHkPrice() {
    return this.discountPercentOnHkPrice;
  }

  public void setDiscountPercentOnHkPrice(Double discountPercentOnHkPrice) {
    this.discountPercentOnHkPrice = discountPercentOnHkPrice;
  }

  public Double getDiscountPercentOnMarkedPrice() {
    return discountPercentOnMarkedPrice;
  }

  public void setDiscountPercentOnMarkedPrice(Double discountPercentOnMarkedPrice) {
    this.discountPercentOnMarkedPrice = discountPercentOnMarkedPrice;
  }

  public Long getQty() {
    return this.qty;
  }

  public void setQty(Long qty) {
    this.qty = qty;
  }

  public Double getDiscountPercentOnShipping() {
    return discountPercentOnShipping;
  }

  public void setDiscountPercentOnShipping(Double discountPercentOnShipping) {
    this.discountPercentOnShipping = discountPercentOnShipping;
  }

  public Boolean isCashback() {
    return isCashback;
  }

  public Boolean Cashback() {
    return isCashback;
  }

  public void setCashback(Boolean cashback) {
    isCashback = cashback;
  }

  public Double getRewardPointCashbackLimit() {
    return rewardPointCashbackLimit;
  }

  public void setRewardPointCashbackLimit(Double rewardPointCashbackLimit) {
    this.rewardPointCashbackLimit = rewardPointCashbackLimit;
  }

  public Double getRewardPointDiscountPercent() {
    return rewardPointDiscountPercent;
  }

  public void setRewardPointDiscountPercent(Double rewardPointDiscountPercent) {
    this.rewardPointDiscountPercent = rewardPointDiscountPercent;
  }

	public Date getRewardPointExpiryDate() {
		return rewardPointExpiryDate;
	}

	public void setRewardPointExpiryDate(Date rewardPointExpiryDate) {
		this.rewardPointExpiryDate = rewardPointExpiryDate;
	}

	public Integer getRewardPointRedeemWithinDays() {
		return rewardPointRedeemWithinDays;
	}

	public void setRewardPointRedeemWithinDays(Integer rewardPointRedeemWithinDays) {
		this.rewardPointRedeemWithinDays = rewardPointRedeemWithinDays;
	}

  public ProductVariant getFreeVariant() {
    return freeVariant;
  }

  public void setFreeVariant(ProductVariant freeVariant) {
    this.freeVariant = freeVariant;
  }

  @Override
  public String toString() {
    return id == null ? "" : id.toString();
  }
}


