package com.hk.domain.offer;
// Generated 15 Sep, 2012 11:50:16 AM by Hibernate Tools 3.2.4.CR1


import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.*;

/**
 * OfferEmailDomain generated by hbm2java
 */
@Entity
@Table (name = "offer_email_domain")
public class OfferEmailDomain implements java.io.Serializable {


	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column (name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn (name = "offer_id", nullable = false)
	private Offer offer;

	@Column (name = "email_domain", nullable = false, length = 100)
	private String emailDomain;

	@Column (name = "active", nullable = false)
	private byte active;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Offer getOffer() {
		return this.offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	public String getEmailDomain() {
		return this.emailDomain;
	}

	public void setEmailDomain(String emailDomain) {
		this.emailDomain = emailDomain;
	}

	public byte getActive() {
		return this.active;
	}

	public void setActive(byte active) {
		this.active = active;
	}

}


