package com.hk.domain.inventory;
// Generated Oct 4, 2011 9:25:12 PM by Hibernate Tools 3.2.4.CR1


import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.hk.domain.sku.SkuItem;
import com.hk.domain.warehouse.Warehouse;

/**
 * Bin generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "bin", uniqueConstraints = @UniqueConstraint(columnNames = "barcode"))
public class Bin implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @Column(name = "barcode", unique = true, nullable = false, length = 45)
  private String barcode;

  @Column(name = "bin")
  private String bin;

  @Column(name = "shelf")
  private String shelf;

  @Column(name = "rack", nullable = false)
  private String rack;

  @Column(name = "aisle", length = 45)
  private String aisle;

  @Column(name = "room", length = 45)
  private String room;

  @Column(name = "floor", length = 45)
  private String floor;

  @Column(name = "building", length = 45)
  private String building;

  @Column(name = "deleted")
  private Boolean deleted = false;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "warehouse_id", nullable = false)
  private Warehouse warehouse;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getBarcode() {
    return this.barcode;
  }

  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  public String getShelf() {
    return shelf;
  }

  public void setShelf(String shelf) {
    this.shelf = shelf;
  }

  public String getRack() {
    return rack;
  }

  public void setRack(String rack) {
    this.rack = rack;
  }

  public String getAisle() {
    return this.aisle;
  }

  public void setAisle(String aisle) {
    this.aisle = aisle;
  }

  public String getRoom() {
    return this.room;
  }

  public void setRoom(String room) {
    this.room = room;
  }

  public String getFloor() {
    return this.floor;
  }

  public void setFloor(String floor) {
    this.floor = floor;
  }

  public String getBuilding() {
    return this.building;
  }

  public void setBuilding(String building) {
    this.building = building;
  }

  public String getBin() {
    return bin;
  }

  public void setBin(String bin) {
    this.bin = bin;
  }

  public Boolean getDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public Warehouse getWarehouse() {
    return warehouse;
  }

  public void setWarehouse(Warehouse warehouse) {
    this.warehouse = warehouse;
  }
}