package com.hk.domain.inventory;
// Generated Dec 15, 2011 3:32:41 PM by Hibernate Tools 3.2.4.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.hk.domain.catalog.product.ProductVariant;
import com.hk.domain.sku.Sku;

/**
 * GrnLineItem generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "grn_line_item", uniqueConstraints = @UniqueConstraint(columnNames = {"goods_received_note_id", "sku_id"}))
public class GrnLineItem implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "goods_received_note_id", nullable = false)
  private GoodsReceivedNote goodsReceivedNote;

  @Column(name = "qty", nullable = false)
  private Long qty;

  @Column(name = "cost_price", nullable = false, precision = 8)
  private Double costPrice;


  @Column(name = "mrp", nullable = false, precision = 8)
  private Double mrp;

  @Transient
  private ProductVariant productVariant;

  @ManyToOne (fetch = FetchType.LAZY)
  @JoinColumn (name = "sku_id", nullable = false)
  private Sku sku;

  @Column(name = "checkedin_qty")
  private Long checkedInQty;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public GoodsReceivedNote getGoodsReceivedNote() {
    return this.goodsReceivedNote;
  }

  public void setGoodsReceivedNote(GoodsReceivedNote goodsReceivedNote) {
    this.goodsReceivedNote = goodsReceivedNote;
  }

  public Long getQty() {
    return this.qty;
  }

  public void setQty(Long qty) {
    this.qty = qty;
  }

  public Double getCostPrice() {
    return this.costPrice;
  }

  public void setCostPrice(Double costPrice) {
    this.costPrice = costPrice;
  }

  public Double getMrp() {
    return this.mrp;
  }

  public void setMrp(Double mrp) {
    this.mrp = mrp;
  }

  public ProductVariant getProductVariant() {
    return productVariant;
  }

  public void setProductVariant(ProductVariant productVariant) {
    this.productVariant = productVariant;
  }

  public Long getCheckedInQty() {
    return checkedInQty != null ? checkedInQty : 0L;
  }

  public void setCheckedInQty(Long checkedInQty) {
    this.checkedInQty = checkedInQty;
  }

  public Sku getSku() {
    return sku;
  }

  public void setSku(Sku sku) {
    this.sku = sku;
  }
}


