package com.hk.domain.inventory;
// Generated Oct 21, 2011 3:25:32 PM by Hibernate Tools 3.2.4.CR1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.hk.domain.catalog.product.ProductVariant;

/**
 * LowInventory generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "low_inventory")
public class LowInventory implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;


  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "product_variant_id", nullable = false, unique = true)
  private ProductVariant productVariant;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "entry_date", nullable = false, length = 19)
  private Date entryDate;


  @Column(name = "alert_email_sent", nullable = false)
  private boolean alertEmailSent;

  @Column(name = "out_of_stock")
  private Boolean outOfStock;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ProductVariant getProductVariant() {
    return productVariant;
  }

  public void setProductVariant(ProductVariant productVariant) {
    this.productVariant = productVariant;
  }

  public Date getEntryDate() {
    return this.entryDate;
  }

  public void setEntryDate(Date entryDate) {
    this.entryDate = entryDate;
  }

  public boolean isAlertEmailSent() {
    return alertEmailSent;
  }

  public boolean getAlertEmailSent() {
    return alertEmailSent;
  }

  public void setAlertEmailSent(boolean alertEmailSent) {
    this.alertEmailSent = alertEmailSent;
  }

  public Boolean isOutOfStock() {
    return outOfStock;
  }

  public Boolean getOutOfStock() {
    return outOfStock;
  }

  public void setOutOfStock(Boolean outOfStock) {
    this.outOfStock = outOfStock;
  }
}


