package com.hk.domain.inventory;
// Generated Nov 8, 2013 1:39:56 PM by Hibernate Tools 3.2.4.CR1


import com.hk.domain.sku.SkuItem;
import com.hk.domain.user.User;

import javax.persistence.*;
import java.util.Date;

/**
 * SkuItemAudit generated by hbm2java
 */
@Entity
@Table(name = "sku_item_audit")
public class SkuItemAudit implements java.io.Serializable {


  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "audited_by", nullable = false)
  private User user;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "sku_item_id", nullable = false, unique = true)
  private SkuItem skuItem;

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "audit_date", nullable = false, length = 19)
  private Date auditDate;

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public User getUser() {
    return this.user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public SkuItem getSkuItem() {
    return this.skuItem;
  }

  public void setSkuItem(SkuItem skuItem) {
    this.skuItem = skuItem;
  }

  public Date getAuditDate() {
    return this.auditDate;
  }

  public void setAuditDate(Date auditDate) {
    this.auditDate = auditDate;
  }

}


