package com.hk.domain.user;
// Generated 3 Mar, 2012 11:57:57 AM by Hibernate Tools 3.2.4.CR1


import javax.persistence.*;

/**
 * B2bUser generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "b2b_user")
@PrimaryKeyJoinColumn(name="b2b_user_id")
public class B2bUser extends User implements java.io.Serializable {

  @Column(name = "tin", length = 45)
  private String tin;

  @Column(name = "dl_number", length = 45)
  private String dlNumber;

  public String getTin() {
    return tin;
  }

  public void setTin(String tin) {
    this.tin = tin;
  }

  public String getDlNumber() {
    return dlNumber;
  }

  public void setDlNumber(String dlNumber) {
    this.dlNumber = dlNumber;
  }
}


